[workspace]
members = ["crates/*"]
exclude = [
  "scripts",
  # Needs nightly
  "crates/uv-trampoline",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.96.0"
homepage = "https://pypi.org/project/uv/"
repository = "https://github.com/astral-sh/uv"
authors = ["uv"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
uv = { version = "0.12.19", path = "crates/uv", default-features = false }
uv-audit = { version = "0.0.86", path = "crates/uv-audit" }
uv-auth = { version = "0.0.86", path = "crates/uv-auth" }
uv-bin-install = { version = "0.0.86", path = "crates/uv-bin-install" }
uv-build-backend = { version = "0.0.86", path = "crates/uv-build-backend" }
uv-build-frontend = { version = "0.0.86", path = "crates/uv-build-frontend" }
uv-cache = { version = "0.0.86", path = "crates/uv-cache" }
uv-cache-info = { version = "0.0.86", path = "crates/uv-cache-info" }
uv-cache-key = { version = "0.0.86", path = "crates/uv-cache-key" }
uv-cli = { version = "0.0.86", path = "crates/uv-cli" }
uv-client = { version = "0.0.86", path = "crates/uv-client" }
uv-configuration = { version = "0.0.86", path = "crates/uv-configuration" }
uv-console = { version = "0.0.86", path = "crates/uv-console" }
uv-dirs = { version = "0.0.86", path = "crates/uv-dirs" }
uv-dispatch = { version = "0.0.86", path = "crates/uv-dispatch" }
uv-distribution = { version = "0.0.86", path = "crates/uv-distribution" }
uv-distribution-filename = { version = "0.0.86", path = "crates/uv-distribution-filename" }
uv-distribution-types = { version = "0.0.86", path = "crates/uv-distribution-types" }
uv-errors = { version = "0.0.86", path = "crates/uv-errors" }
uv-extract = { version = "0.0.86", path = "crates/uv-extract" }
uv-fastid = { version = "0.0.86", path = "crates/uv-fastid" }
uv-flags = { version = "0.0.86", path = "crates/uv-flags" }
uv-fs = { version = "0.0.86", path = "crates/uv-fs", features = [
  "serde",
  "tokio",
] }
uv-git = { version = "0.0.86", path = "crates/uv-git" }
uv-git-types = { version = "0.0.86", path = "crates/uv-git-types" }
uv-globfilter = { version = "0.0.86", path = "crates/uv-globfilter" }
uv-install-wheel = { version = "0.0.86", path = "crates/uv-install-wheel", default-features = false }
uv-installer = { version = "0.0.86", path = "crates/uv-installer" }
uv-keyring = { version = "0.0.86", path = "crates/uv-keyring" }
uv-lock = { version = "0.0.86", path = "crates/uv-lock" }
uv-logging = { version = "0.0.86", path = "crates/uv-logging" }
uv-macros = { version = "0.0.86", path = "crates/uv-macros" }
uv-metadata = { version = "0.0.86", path = "crates/uv-metadata" }
uv-netrc = { version = "0.0.86", path = "crates/uv-netrc" }
uv-normalize = { version = "0.0.86", path = "crates/uv-normalize" }
uv-once-map = { version = "0.0.86", path = "crates/uv-once-map" }
uv-options-metadata = { version = "0.0.86", path = "crates/uv-options-metadata" }
uv-performance-memory-allocator = { version = "0.0.86", path = "crates/uv-performance-memory-allocator" }
uv-pep440 = { version = "0.0.86", path = "crates/uv-pep440", features = [
  "tracing",
  "rkyv",
  "version-ranges",
] }
uv-pep508 = { version = "0.0.86", path = "crates/uv-pep508", features = [
  "non-pep508-extensions",
] }
uv-platform = { version = "0.0.86", path = "crates/uv-platform" }
uv-platform-tags = { version = "0.0.86", path = "crates/uv-platform-tags" }
uv-preview = { version = "0.0.86", path = "crates/uv-preview" }
uv-publish = { version = "0.0.86", path = "crates/uv-publish" }
uv-pypi-types = { version = "0.0.86", path = "crates/uv-pypi-types" }
uv-python = { version = "0.0.86", path = "crates/uv-python" }
uv-redacted = { version = "0.0.86", path = "crates/uv-redacted" }
uv-requirements = { version = "0.0.86", path = "crates/uv-requirements" }
uv-requirements-txt = { version = "0.0.86", path = "crates/uv-requirements-txt" }
uv-resolver = { version = "0.0.86", path = "crates/uv-resolver" }
uv-resolver-types = { version = "0.0.86", path = "crates/uv-resolver-types" }
uv-scripts = { version = "0.0.86", path = "crates/uv-scripts" }
uv-settings = { version = "0.0.86", path = "crates/uv-settings" }
uv-shell = { version = "0.0.86", path = "crates/uv-shell" }
uv-small-str = { version = "0.0.86", path = "crates/uv-small-str" }
uv-state = { version = "0.0.86", path = "crates/uv-state" }
uv-static = { version = "0.0.86", path = "crates/uv-static" }
uv-test = { version = "0.0.86", path = "crates/uv-test" }
uv-threads = { version = "0.0.86", path = "crates/uv-threads" }
uv-toml = { version = "0.0.86", path = "crates/uv-toml" }
uv-tool = { version = "0.0.86", path = "crates/uv-tool" }
uv-torch = { version = "0.0.86", path = "crates/uv-torch" }
uv-trampoline-builder = { version = "0.0.86", path = "crates/uv-trampoline-builder" }
uv-types = { version = "0.0.86", path = "crates/uv-types" }
uv-unix = { version = "0.0.86", path = "crates/uv-unix" }
uv-version = { version = "0.12.19", path = "crates/uv-version" }
uv-virtualenv = { version = "0.0.86", path = "crates/uv-virtualenv" }
uv-warnings = { version = "0.0.86", path = "crates/uv-warnings" }
uv-windows = { version = "0.0.86", path = "crates/uv-windows" }
uv-workspace = { version = "0.0.86", path = "crates/uv-workspace" }

ambient-id = { version = "0.0.11", default-features = false, features = [
  "reqwest-middleware",
] }
anstream = { version = "1.0.0", default-features = false, features = ["auto", "wincon"] }
anyhow = { version = "1.0.89", default-features = false, features = ["std"] }
arcstr = { version = "1.2.0", default-features = false }
arrayvec = { version = "0.7.6", default-features = false }
astral-tokio-tar = { version = "0.7.0", default-features = false }
async-channel = { version = "2.3.1", default-features = false, features = ["std"] }
async-compression = { version = "0.4.12", default-features = false, features = [
  "gzip",
  "tokio",
  "zstd",
] }
async-trait = { version = "0.1.82", default-features = false }
async_http_range_reader = { version = "0.11.1", package = "astral_async_http_range_reader", default-features = false }
async_zip = { version = "0.0.20", package = "astral_async_zip", default-features = false, features = [
  "deflate",
  "zstd",
] }
axoupdater = { version = "0.10.0", default-features = false }
backon = { version = "1.3.0", default-features = false, features = [
  "std",
  "std-blocking-sleep",
  "tokio-sleep",
] }
base64 = { version = "0.22.1", default-features = false, features = ["std"] }
bitflags = { version = "2.6.0", default-features = false }
blake2 = { version = "0.11.0-rc.6", default-features = false }
blake3 = { version = "1.8.5", default-features = false, features = ["std"] }
boxcar = { version = "0.2.5", default-features = false }
bytecheck = { version = "0.8.0", default-features = false }
cargo-util = { version = "0.2.14", default-features = false }
clap = { version = "4.5.17", default-features = false, features = [
  "color",
  "derive",
  "env",
  "error-context",
  "help",
  "std",
  "string",
  "suggestions",
  "usage",
  "wrap_help",
] }
clap_complete_command = { version = "0.6.1", default-features = false, features = ["nushell"] }
configparser = { version = "3.1.0", default-features = false }
console = { version = "0.16.0", default-features = false, features = ["std"] }
csv = { version = "1.3.0", default-features = false }
ctrlc = { version = "3.4.5", default-features = false }
cyclonedx-bom = { version = "0.8.1", default-features = false }
data-encoding = { version = "2.6.0", default-features = false, features = ["alloc"] }
diskus = { version = "0.9.0", default-features = false }
dotenvy = { version = "0.15.7", default-features = false }
dunce = { version = "1.0.5", default-features = false }
editpe = { version = "0.2.4", default-features = false, features = ["std"] }
either = { version = "1.13.0", default-features = false, features = ["std"] }
encoding_rs_io = { version = "0.1.7", default-features = false }
embed-manifest = { version = "1.5.0", default-features = false }
enumflags2 = { version = "0.7.12", default-features = false }
etcetera = { version = "0.11.0", default-features = false }
fastrand = { version = "2.3.0", default-features = false, features = ["std"] }
flate2 = { version = "1.0.33", default-features = false, features = [
  "zlib-rs",
] }
fs-err = { version = "3.2.2", default-features = false, features = ["tokio"] }
futures = { version = "0.3.30", default-features = false, features = ["async-await", "executor"] }
futures-lite = { version = "2.6.1", default-features = false, features = ["std"] }
glob = { version = "0.3.1", default-features = false }
globset = { version = "0.4.15", default-features = false }
globwalk = { version = "0.9.1", default-features = false }
goblin = { version = "0.10.0", default-features = false, features = [
  "std",
  "elf32",
  "elf64",
  "endian_fd",
  "pe32",
  "pe64",
] }
h2 = { version = "0.4.7", default-features = false }
hashbrown = { version = "0.17.0", default-features = false, features = [
  "equivalent",
  "inline-more",
] }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
html-escape = { version = "0.2.13", default-features = false }
http = { version = "1.1.0", default-features = false, features = ["std"] }
http-content-range = { version = "0.2.4", default-features = false }
indexmap = { version = "2.5.0", default-features = false, features = ["std"] }
indicatif = { version = "0.18.0", default-features = false, features = ["unicode-width"] }
indoc = { version = "2.0.5", default-features = false }
itertools = { version = "0.14.0", default-features = false, features = ["use_std"] }
jiff = { version = "0.2.0", default-features = false, features = [
  "perf-inline",
  "serde",
  "std",
  "tz-fat",
  "tz-system",
  "tzdb-bundle-platform",
  "tzdb-concatenated",
  "tzdb-zoneinfo",
] }
junction = { version = "2.0.0", default-features = false, features = ["unstable_admin"] }
libc = { version = "0.2.0", default-features = false, features = ["std"] }
linux-raw-sys = { version = "0.12.1", default-features = false, features = ["ioctl"] }
mailparse = { version = "0.16.0", default-features = false }
md-5 = { version = "0.11.0", default-features = false }
memchr = { version = "2.7.4", default-features = false, features = ["std"] }
nix = { version = "0.31.2", default-features = false, features = ["resource", "signal"] }
owo-colors = { version = "4.1.0", default-features = false }
papaya = { version = "0.2.5", default-features = false }
path-slash = { version = "0.2.1", default-features = false }
pathdiff = { version = "0.2.1", default-features = false }
percent-encoding = { version = "2.3.1", default-features = false, features = ["std"] }
petgraph = { version = "0.8.0", default-features = false, features = ["std"] }
proc-macro2 = { version = "1.0.86", default-features = false, features = ["proc-macro"] }
procfs = { version = "0.18.0", default-features = false, features = ["flate2"] }
pubgrub = { version = "0.6.1", package = "astral-pubgrub", default-features = false }
quote = { version = "1.0.37", default-features = false, features = ["proc-macro"] }
rand = { version = "0.10.2", default-features = false, features = ["thread_rng"] }
rayon = { version = "1.10.0", default-features = false }
ref-cast = { version = "1.0.24", default-features = false }
reflink-copy = { version = "0.1.19", default-features = false }
regex = { version = "1.13.0", default-features = false, features = ["perf", "std", "unicode"] }
regex-automata = { version = "0.4.8", default-features = false, features = [
  "dfa-build",
  "dfa-search",
  "perf",
  "std",
  "syntax",
] }
reqsign = { version = "0.20.0", features = [
  "aws",
  "azure",
  "google",
  "default-context",
], default-features = false }
reqwest = { version = "0.13.1", default-features = false, features = [
  "json",
  "gzip",
  "deflate",
  "zstd",
  "stream",
  "system-proxy",
  "rustls",
  "socks",
  "multipart",
  "http2",
  "query",
] }
reqwest-middleware = { version = "0.5.1", package = "astral-reqwest-middleware", default-features = false, features = [
  "multipart",
  "query",
] }
reqwest-retry = { version = "0.9.1", package = "astral-reqwest-retry", default-features = false, features = [
  "tracing",
] }
rkyv = { version = "0.8.14", default-features = false, features = ["bytecheck", "std"] }
rmp-serde = { version = "1.3.0", default-features = false }
rustc-hash = { version = "2.0.0", default-features = false, features = ["std"] }
rustls-native-certs = { version = "0.8.3", default-features = false }
rustls-pki-types = { version = "1.14.0", default-features = false, features = ["alloc"] }
rustix = { version = "1.0.0", default-features = false, features = [
  "fs",
  "std",
  "system",
] }
same-file = { version = "1.0.6", default-features = false }
schemars = { version = "1.0.0", default-features = false, features = ["derive", "std", "url2"] }
seahash = { version = "4.1.0", default-features = false }
secret-service = { version = "5.0.0", default-features = false, features = [
  "rt-tokio-crypto-rust",
] }
shellexpand = { version = "3.1.0", default-features = false, features = [
  "base-0",
  "tilde",
  "path",
] }
security-framework = { version = "3", default-features = false }
self-replace = { version = "1.5.0", default-features = false }
serde = { version = "1.0.210", default-features = false, features = ["derive", "rc", "std"] }
serde-untagged = { version = "0.1.6", default-features = false }
serde_json = { version = "1.0.128", default-features = false, features = ["std"] }
sha2 = { version = "0.11.0", default-features = false }
smallvec = { version = "1.13.2", default-features = false }
spdx = { version = "0.13.0", default-features = false }
syn = { version = "3.0.0", default-features = false, features = [
  "clone-impls",
  "derive",
  "parsing",
  "printing",
  "proc-macro",
] }
tar-codec = { version = "0.0.14", default-features = false }
target-lexicon = { version = "0.13.0", default-features = false }
tempfile = { version = "3.14.0", default-features = false, features = ["getrandom"] }
terminal_size = { version = "0.4.2", default-features = false }
textwrap = { version = "0.16.1", default-features = false, features = ["smawk", "unicode-width"] }
thiserror = { version = "2.0.0", default-features = false, features = ["std"] }
astral-tl = { version = "0.8.0", default-features = false }
tokio = { version = "1.40.0", default-features = false, features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "process",
  "rt",
  "signal",
  "sync",
  "time",
] }
tokio-stream = { version = "0.1.16", default-features = false }
tokio-util = { version = "0.7.12", default-features = false, features = ["compat", "io"] }
toml = { version = "1.1.0", default-features = false, features = [
  "display",
  "fast_hash",
  "parse",
  "serde",
  "std",
] }
toml_edit = { version = "0.25.8", default-features = false, features = [
  "display",
  "parse",
  "serde",
] }
toml_parser = { version = "1.1.0", default-features = false, features = ["alloc", "simd"] }
toml_writer = { version = "1.1.0", default-features = false, features = ["alloc"] }
tracing = { version = "0.1.40", default-features = false, features = ["attributes", "std"] }
tracing-durations-export = { version = "0.3.0", default-features = false, features = ["plot"] }
tracing-subscriber = { version = "0.3.18", default-features = false, features = [
  "ansi",
  "fmt",
  "smallvec",
  "std",
  "tracing-log",
] } # Base feature set for uv_build; uv activates extra features
tracing-test = { version = "0.2.5", default-features = false }
tracing-tree = { version = "0.4.0", default-features = false, features = ["tracing-log"] }
unicode-width = { version = "0.2.0", default-features = false }
unscanny = { version = "0.1.0", default-features = false }
url = { version = "2.5.2", default-features = false, features = ["serde", "std"] }
version-ranges = { version = "0.2.2", package = "astral-version-ranges", default-features = false }
walkdir = { version = "2.5.0", default-features = false }
webpki-root-certs = { version = "1", default-features = false }
which = { version = "8.0.0", default-features = false, features = ["real-sys"] }
windows = { version = "0.61.0", default-features = false, features = [
  "std",
  "Win32_Devices_DeviceAndDriverInstallation",
  "Win32_Foundation",
  "Win32_Globalization",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_Console",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Environment",
  "Win32_System_IO",
  "Win32_System_Ioctl",
  "Win32_System_JobObjects",
  "Win32_System_Kernel",
  "Win32_System_LibraryLoader",
  "Win32_System_Registry",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
] }
windows-registry = { version = "0.5.0", default-features = false, features = ["std"] }
windows-version = { version = "0.1.6", default-features = false }
wiremock = { version = "0.6.4", default-features = false }
zeroize = { version = "1.8.1", default-features = false, features = ["alloc"] }

# dev-dependencies
assert_cmd = { version = "2.0.16", default-features = false }
assert_fs = { version = "1.1.2", default-features = false }
byteorder = { version = "1.5.0", default-features = false, features = ["std"] }
bytes = { version = "1.10.1", default-features = false, features = ["std"] }
filetime = { version = "0.2.25", default-features = false }
http-body-util = { version = "0.1.2", default-features = false }
hyper = { version = "1.4.1", default-features = false, features = ["http1", "server"] }
hyper-util = { version = "0.1.8", default-features = false, features = [
  "http1",
  "server",
  "tokio",
] }
ignore = { version = "0.4.23", default-features = false }
insta = { version = "1.46.0", default-features = false, features = [
  "colors",
  "filters",
  "json",
  "redactions",
] }
predicates = { version = "3.1.2", default-features = false }
rcgen = { version = "0.14.5", features = [
  "crypto",
  "pem",
  "ring",
], default-features = false }
rustls = { version = "0.23.36", default-features = false, features = [
  "aws_lc_rs",
  "logging",
  "prefer-post-quantum",
  "std",
  "tls12",
] }
similar = { version = "3.0.0", default-features = false, features = ["std", "text"] }
webpki = { version = "0.103.10", package = "rustls-webpki", default-features = false, features = [
  "std",
] }
x509-parser = { version = "0.18.0", default-features = false }
temp-env = { version = "0.3.6", default-features = false, features = ["async_closure"] }
test-case = { version = "3.3.1", default-features = false }
test-log = { version = "0.2.16", features = [
  "trace",
], default-features = false }
tokio-rustls = { version = "0.26.2", default-features = false }

[workspace.lints.rust]
unsafe_code = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -2 }
# Allowed pedantic lints
char_lit_as_u8 = "allow"
collapsible_else_if = "allow"
collapsible_if = "allow"
implicit_hasher = "allow"
map_unwrap_or = "allow"
match_same_arms = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
similar_names = "allow"
struct_excessive_bools = "allow"
too_many_arguments = "allow"
too_many_lines = "allow"
used_underscore_binding = "allow"
# Disallowed restriction lints
print_stdout = "warn"
print_stderr = "warn"
dbg_macro = "warn"
empty_drop = "warn"
empty_structs_with_brackets = "warn"
exit = "warn"
get_unwrap = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
rest_pat_in_fully_bound_structs = "warn"
if_not_else = "allow"
use_self = "warn"

# Diagnostics are not actionable: Enable once https://github.com/rust-lang/rust-clippy/issues/13774 is resolved.
large_stack_arrays = "allow"

# Skip type and variable debug information to speed up local builds while retaining
# file names and line numbers for backtraces. This reduced total time by 20% versus
# full debug information in one warm edit/build/test replay on macOS:
# https://github.com/astral-sh/uv/pull/21546
[profile.dev]
debug = "line-tables-only"

[profile.release]
strip = true
lto = "fat"
# This will still show a panic message, we only skip the unwind.
panic = "abort"

# This profile is meant to mimic the `release` profile as closely as
# possible, but using settings that are more beneficial for iterative
# development. That is, the `release` profile is intended for actually
# building the release, where as `profiling` is meant for building `uv`
# for running benchmarks.
#
# The main differences here are to avoid stripping debug information
# and disabling lto. This does result in a mismatch between our release
# configuration and our benchmarking configuration, which is unfortunate.
# But compile times with `lto = true` are completely untenable:
#
#     $ cargo b --profile profiling -p uv
#        Compiling uv-cli v0.0.1 (/home/andrew/astral/uv/crates/uv-cli)
#        Compiling uv v0.2.34 (/home/andrew/astral/uv/crates/uv)
#         Finished `profiling` profile [optimized + debuginfo] target(s) in 3m 47s
#
# Using `lto = "thin"` brings a massive improvement, but it's still slow:
#
#     $ cargo b --profile profiling -p uv
#        Compiling uv v0.2.34 (/home/andrew/astral/uv/crates/uv)
#         Finished `profiling` profile [optimized + debuginfo] target(s) in 53.98s
#
# But with `lto = false`:
#
#     $ cargo b --profile profiling -p uv
#        Compiling uv v0.2.34 (/home/andrew/astral/uv/crates/uv)
#         Finished `profiling` profile [optimized + debuginfo] target(s) in 30.09s
#
# We get more reasonable-ish compile times. At least, it's not enough
# time to get up and get a cup of coffee before it completes.
#
# This setup does risk that we are measuring something in benchmarks
# that we are shipping, but in order to make those two the same, we'd
# either need to make compile times way worse for development, or take
# a hit to binary size and a slight hit to runtime performance in our
# release builds.
[profile.profiling]
inherits = "release"
strip = false
debug = "full"
lto = false

# Profile for fast test execution: Skip debug info generation, and
# apply basic optimization, which speed up build and running tests.
[profile.fast-build]
inherits = "dev"
opt-level = 1
# Disable the local ThinLTO implicitly enabled by `opt-level = 1`.
lto = "off"
debug = 0
strip = "debuginfo"

# Profile for fast test execution with nightly's panic-abort-tests feature.
[profile.fast-build-nightly]
inherits = "fast-build"
panic = "abort"

# Profile for faster builds: Skip debug info generation, for faster
# builds of smaller binaries.
[profile.no-debug]
inherits = "dev"
debug = 0
strip = "debuginfo"

# Profile for fast development builds with aborting panics.
[profile.no-debug-nightly]
inherits = "no-debug"
panic = "abort"

# Profile to build a minimally sized binary for uv-build
[profile.minimal-size]
inherits = "release"
opt-level = "z"
codegen-units = 1

# The profile that 'cargo dist' will build with.
[profile.dist]
inherits = "release"
