ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim as base

RUN apt-get update
RUN apt-get install -y curl

ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

ADD scripts/requirements/compiled/all-kinds.txt /requirements.txt

ENV RUST_LOG=trace
RUN /root/.cargo/bin/uv pip install -r /requirements.txt --system -v
