target-version = "py312"
per-file-target-version = {
  "scripts/check_system_python.py" = "py37",
  "scripts/create-python-mirror.py" = "py38",
}
exclude = [
  "crates/uv-virtualenv/src/activator/activate_this.py",
  "crates/uv-virtualenv/src/_virtualenv.py",
  "test/ecosystem",
  "test/workspaces",
  "test/packages",
]

[lint]
extend-select = ["I", "B"]

[lint.per-file-ignores]
"__init__.py" = ["F403", "F405"]
# This script intentionally runs on Python 3.6, below Ruff's minimum target version.
"scripts/check_system_python.py" = ["FA100", "UP036"]
