# Dependency metadata from https://github.com/openai/openai-python/blob/6d9262d5c666a1e4d47f63178db907ba3087ac5d/pyproject.toml

[project]
name = "openai"
version = "2.44.0"
requires-python = ">= 3.9"
dependencies = [
    "httpx>=0.23.0, <1",
    "pydantic>=1.9.0, <3",
    "typing-extensions>=4.14, <5",
    "anyio>=3.5.0, <5",
    "distro>=1.7.0, <2",
    "sniffio",
    "tqdm > 4",
    "jiter>=0.10.0, <1",
]

[project.optional-dependencies]
aiohttp = [
    "aiohttp",
    "httpx_aiohttp>=0.1.9",
]
realtime = [
    "websockets >= 13, < 16",
]
datalib = [
    "numpy >= 1",
    "pandas >= 1.2.3",
    "pandas-stubs >= 1.1.0.11",
]
voice_helpers = [
    "sounddevice>=0.5.1",
    "numpy>=2.0.2",
]
bedrock = [
    "botocore>=1.40.0,<1.43; python_version < '3.10'",
    "botocore>=1.40.0,<2; python_version >= '3.10'",
]

[build-system]
requires = [
    "hatchling==1.26.3",
    "hatch-fancy-pypi-readme",
]
build-backend = "hatchling.build"
