# Dependency metadata from https://github.com/pallets/flask/blob/06ea505ce2b2042af26e96d35ebf159af7c0869d/pyproject.toml

[project]
name = "Flask"
version = "3.2.0.dev"
requires-python = ">=3.10"
dependencies = [
    "blinker>=1.9.0",
    "click>=8.1.3",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.2",
    "markupsafe>=2.1.1",
    "werkzeug>=3.1.0",
]

[project.optional-dependencies]
async = [
    "asgiref>=3.2",
]
dotenv = [
    "python-dotenv",
]

[dependency-groups]
dev = [
    "ruff",
    "tox",
    "tox-uv",
]
docs = [
    "pallets-sphinx-themes",
    "sphinx<9",
    "sphinx-tabs",
    "sphinxcontrib-log-cabinet",
]
docs-auto = [
    "sphinx-autobuild",
]
gha-update = [
    "gha-update ; python_full_version >= '3.12'",
]
pre-commit = [
    "pre-commit",
    "pre-commit-uv",
]
tests = [
    "asgiref",
    "pytest",
    "python-dotenv",
]
typing = [
    "asgiref",
    "cryptography",
    "mypy",
    "pyright",
    "pytest",
    "python-dotenv",
    "types-contextvars",
    "types-dataclasses",
]

[tool.uv]
default-groups = [
    "dev",
    "pre-commit",
    "tests",
    "typing",
]

[build-system]
requires = [
    "flit_core>=3.11,<4",
]
build-backend = "flit_core.buildapi"
