[project]
name = "pyx-member-23"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "msgspec==0.21.1",
    "nanoid==2.0.0",
    "packaging==26.0",
    "packaging-legacy==23.0.post0",
    "pyx-member-04",
    "sqlalchemy==2.0.49",
]

[dependency-groups]
dev = [
    "deptry==0.25.1",
    "freezegun==1.5.5",
    "inline-snapshot==0.32.6",
    "pytest==9.0.3",
    "pyx-member-33",
    "ruff==0.15.18",
    "ty==0.0.51",
]
