[project]
name = "pyx-member-33"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "aiohttp==3.14.1",
    "aioresponses==0.7.8",
    "aws-lambda-powertools==3.27.0",
    "boto3",
    "coverage==7.13.5",
    "httpx",
    "moto[kms,s3,sqs,secretsmanager]==5.1.22",
    "opentelemetry-exporter-otlp-proto-http==1.41.0",
    "opentelemetry-sdk==1.41.0",
    "pydantic==2.12.5",
    "pyx-member-03",
    "pyx-member-05",
    "pyx-member-06",
    "pyx-member-09",
    "pyx-member-23",
    "pyx-member-24",
    "pyx-member-30",
    "pytest==9.0.3",
    "pytest-asyncio==1.3.0",
    "python-dotenv==1.2.2",
    "sqlalchemy",
    "trove-classifiers",
    "types-boto3-kms",
    "types-boto3-s3",
    "types-boto3-secretsmanager",
    "types-boto3-sqs",
    "workos==5.46.0",
    "sentry-sdk==2.57.0",
    "urllib3==2.7.0",
    "packaging==26.0",
    "id==1.6.1",
    "dirty-equals==0.11",
    "pyjwt==2.13.0",
    "pyx-member-04",
]

[dependency-groups]
dev = [
    "deptry==0.25.1",
    "ty==0.0.51",
]
