[package]
name = "uv"
version = "0.12.15"
description = "A Python package and project manager"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = "https://docs.astral.sh/uv"
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
default-run = "uv"

[lints]
workspace = true

[dependencies]
uv-app = { workspace = true }
uv-performance-memory-allocator = { workspace = true, optional = true }
uv-test = { workspace = true, optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
uv-windows = { workspace = true }

[build-dependencies]
uv-static = { workspace = true }
uv-version = { workspace = true }

embed-manifest = { workspace = true }

[dev-dependencies]
uv-cache = { workspace = true }
uv-cache-key = { workspace = true }
uv-client = { workspace = true }
uv-extract = { workspace = true }
uv-fs = { workspace = true }
uv-install-wheel = { workspace = true, default-features = false }
uv-normalize = { workspace = true }
uv-pep440 = { workspace = true }
uv-pep508 = { workspace = true }
uv-platform = { workspace = true }
# Enable HTTP trusted-publishing endpoints for integration tests.
uv-publish = { workspace = true, features = ["test"] }
uv-python = { workspace = true }
uv-requirements = { workspace = true }
uv-resolver = { workspace = true }
uv-static = { workspace = true }
uv-test = { workspace = true }
uv-trampoline-builder = { workspace = true }
uv-version = { workspace = true }

anyhow = { workspace = true }
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
async_zip = { workspace = true }
axoupdater = { workspace = true, features = [
  "github_releases",
  "tokio",
] }
backon = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
dunce = { workspace = true }
filetime = { workspace = true }
flate2 = { workspace = true, default-features = false }
fs-err = { workspace = true, features = ["tokio"] }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
indoc = { workspace = true }
insta = { workspace = true }
predicates = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["blocking"], default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tar-codec = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }
which = { workspace = true }
wiremock = { workspace = true }

[features]
default = ["performance", "test-defaults"]
native-auth = []
# Use better memory allocators, etc.
performance = ["performance-memory-allocator"]
performance-memory-allocator = ["dep:uv-performance-memory-allocator"]

# Adds self-update functionality. This feature is only enabled for uv's cargo-dist installer
# and should be left unselected when building uv for package managers.
self-update = ["uv-app/self-update"]

# Features for development only.
tracing-durations-export = ["uv-app/tracing-durations-export", "uv-test/tracing-durations-export"]

# Features that only apply when running tests, no-ops otherwise.
test-defaults = [
  "test-crates-io",
  "test-git",
  "test-git-lfs",
  "test-pypi",
  "test-r2",
  "test-python",
  "test-python-managed",
  "test-python-eol",
  "test-slow",
  "test-ecosystem",
  "test-universal"
]
# Introduces a testing dependency on crates.io.
test-crates-io = []
# Introduces a testing dependency on Git.
test-git = ["uv-test?/git"]
# Introduces a testing dependency on Git LFS.
test-git-lfs = ["test-git"]
# Introduces a testing dependency on PyPI.
test-pypi = ["uv-app/test-pypi"]
# Introduces a testing dependency on R2.
test-r2 = []
# Introduces a testing dependency on a local Python installation.
test-python = []
# Introduces a testing dependency on a local Python installation with specific patch versions.
test-python-patch = []
# Introduces a testing dependency on a local Python installation with an EOL version.
test-python-eol = []
# Introduces a testing dependency on managed Python installations.
test-python-managed = []
# Include "slow" test cases.
test-slow = []
# Includes test cases that require ecosystem packages
test-ecosystem = []
# Includes test cases for universal, platform-independent behavior.
test-universal = []
# Includes test cases that write to the Windows registry. These tests mutate
# global state (the Windows registry).
# We don't run these tests by default locally; the CI for Windows enables them.
test-windows-registry = []
# Build uvw binary on Windows
windows-gui-bin = []

[package.metadata.cargo-shear]
# The uv crate has uv-test as dev-dependency. We want that by default,
# uv runs tests with `uv-test/git`, so it's a default feature in uv. The
# problem is that uv-test is only a dev dependency, which gets stripped by
# `cargo install`, and `cargo install` fails with a missing crate error.
# As workaround, we make `uv-test` a regular optional dependency. It's never
# used as a regular dependency, but it allows using `uv-test?/git` as default
# feature.
ignored = ["uv-test", "uv-publish"]

[package.metadata.dist]
dist = true

[[bin]]
name = "uvw"
required-features = ["windows-gui-bin"]
