[project]
name = "pyx-member-03"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "boto3==1.42.88",
    "botocore==1.42.88",
    "pyx-member-32",
]

[dependency-groups]
dev = [
    "deptry==0.25.1",
    "dirty-equals==0.11",
    "inline-snapshot==0.32.6",
    "msgspec==0.21.1",
    "pyx-member-23",
    "pyx-member-30",
    "pyx-member-33",
    "ty==0.0.51",
]
