[project]
name = "pyx-member-30"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "abi3audit==0.0.26",
    "aiofiles==25.1.0",
    "aiohttp==3.14.1",
    "annotated-types==0.7.0",
    "asgi-correlation-id==4.3.4",
    "auditwheel==6.6.0",
    "boto3[crt]==1.42.88",
    "brotli-asgi==1.6.0",
    "chevron-blue==0.3.0",
    "cryptography==48.0.1",
    "fastapi==0.135.3",
    "greenlet==3.4.0",
    "httpx==0.28.1",
    "msgspec==0.21.1",
    "opentelemetry-exporter-otlp-proto-http==1.41.0",
    "opentelemetry-instrumentation-fastapi==0.62b0",
    "opentelemetry-sdk==1.41.0",
    "packaging-legacy==23.0.post0",
    "packaging==26.0",
    "posthog==7.11.0",
    "pydantic-core==2.41.5",
    "pydantic-extra-types==2.11.1",
    "pydantic==2.12.5",
    "pyjwt==2.13.0",
    "python-multipart==0.0.31",
    "pyx-member-03",
    "pyx-member-05",
    "pyx-member-06",
    "pyx-member-09[aws]",
    "pyx-member-23",
    "pyx-member-24[aws]",
    "pyx-member-25",
    "pyx-member-26",
    "pyx-member-28[aws]",
    "pyx-member-29",
    "pyx-member-31",
    "pyx-member-32",
    "pyx-member-34",
    "pyx-member-35",
    "rfc3986==2.0.0",
    "sentry-sdk[fastapi]==2.57.0",
    "sqlalchemy==2.0.49",
    "stamina==25.2.0",
    "starlette==1.3.1",
    "stripe==14.5.0a1",
    "trove-classifiers==2026.1.14.14",
    "types-boto3[lambda]==1.42.88",
    "uvicorn[standard]==0.44.0",
    "workos==5.46.0",
    "xxhash==3.6.0",
    "zstd-asgi==1.0",
]

[dependency-groups]
dev = [
    "coverage==7.13.5",
    "deptry==0.25.1",
    "dirty-equals==0.11",
    "fastapi[standard]==0.135.3",
    "freezegun==1.5.5",
    "inline-snapshot==0.32.6",
    "pytest==9.0.3",
    "pytest-asyncio==1.3.0",
    "pyx-member-33",
    "respx==0.23.1",
    "ruff==0.15.18",
    "ty==0.0.51",
    "types-aiofiles==25.1.0.20260409",
]
