use anyhow::Result;
use assert_fs::prelude::*;
use indoc::indoc;
use predicates::prelude::predicate;

use uv_static::EnvVars;
use uv_test::uv_snapshot;

#[test]
fn project_commands_without_workspace() -> Result<()> {
    let context = uv_test::test_context!("3.12");

    context
        .temp_dir
        .child("pyproject.toml")
        .write_str(indoc! {r#"
        [project]
        name = "root"
        version = "0.1.0"
        requires-python = ">=3.12"

        [tool.uv.workspace]
        members = ["child"]
    "#})?;

    let child = context.temp_dir.child("child");
    child.child("pyproject.toml").write_str(indoc! {r#"
        [project]
        name = "child"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["dependency"]

        [tool.uv.sources]
        dependency = { path = "../dependency" }
    "#})?;

    context
        .temp_dir
        .child("dependency")
        .child("pyproject.toml")
        .write_str(indoc! {r#"
        [project]
        name = "dependency"
        version = "0.1.0"
        requires-python = ">=3.12"

        [tool.uv]
        package = false
    "#})?;

    uv_snapshot!(context.filters(), context.lock().current_dir(&child).arg("--no-workspace"), @"
    success: true
    exit_code: 0
    ----- stdout -----

    ----- stderr -----
    Using CPython 3.12.[X] interpreter at: [PYTHON-3.12]
    Resolved 2 packages in [TIME]
    ");
    context
        .temp_dir
        .child("uv.lock")
        .write_str("root lockfile\n")?;

    uv_snapshot!(context.filters(), context.tree().current_dir(&child).arg("--no-workspace").arg("--frozen").arg("--universal"), @"
    success: true
    exit_code: 0
    ----- stdout -----
    child v0.1.0
    └── dependency v0.1.0

    ----- stderr -----
    ");

    uv_snapshot!(context.filters(), context.export().current_dir(&child).arg("--no-workspace").arg("--frozen").arg("--no-hashes"), @"
    success: true
    exit_code: 0
    ----- stdout -----
    # This file was autogenerated by uv via the following command:
    #    uv export --cache-dir [CACHE_DIR] --no-workspace --frozen --no-hashes

    ----- stderr -----
    ");

    uv_snapshot!(context.filters(), context.run().current_dir(&child).env_remove(EnvVars::VIRTUAL_ENV).arg("--no-workspace").arg("--frozen").arg("python").arg("-c").arg("print('child')"), @"
    success: true
    exit_code: 0
    ----- stdout -----
    child

    ----- stderr -----
    Using CPython 3.12.[X] interpreter at: [PYTHON-3.12]
    Creating virtual environment at: .venv
    Checked in [TIME]
    ");

    uv_snapshot!(context.filters(), context.version().current_dir(&child).arg("0.2.0").arg("--no-workspace").arg("--no-sync"), @"
    success: true
    exit_code: 0
    ----- stdout -----
    child 0.1.0 => 0.2.0

    ----- stderr -----
    Resolved 2 packages in [TIME]
    ");

    uv_snapshot!(context.filters(), context.remove().current_dir(&child).arg("dependency").arg("--no-workspace").arg("--no-sync"), @"
    success: true
    exit_code: 0
    ----- stdout -----

    ----- stderr -----
    Resolved 1 package in [TIME]
    ");

    assert_eq!(context.read("uv.lock"), "root lockfile\n");
    child.child("uv.lock").assert(predicate::path::is_file());

    Ok(())
}

#[test]
fn virtual_project_commands_without_workspace() -> Result<()> {
    let context = uv_test::test_context!("3.12");

    context
        .temp_dir
        .child("pyproject.toml")
        .write_str(indoc! {r#"
        [dependency-groups]
        dev = []

        [tool.uv.workspace]
        members = ["child"]
    "#})?;
    context
        .temp_dir
        .child("child")
        .child("pyproject.toml")
        .write_str(indoc! {r#"
        [project]
        name = "child"
        version = "0.1.0"
        requires-python = ">=3.12"
    "#})?;

    uv_snapshot!(context.filters(), context.lock().arg("--no-workspace"), @"
    success: true
    exit_code: 0
    ----- stdout -----

    ----- stderr -----
    warning: No `requires-python` value found in the workspace. Defaulting to `>=3.12`.
    Resolved in [TIME]
    ");

    uv_snapshot!(context.filters(), context.tree().arg("--no-workspace").arg("--frozen"), @"
    success: true
    exit_code: 0
    ----- stdout -----

    ----- stderr -----
    ");

    Ok(())
}
