use std::collections::BTreeMap;

use anyhow::{Context, Result};
use assert_fs::fixture::ChildPath;
use assert_fs::prelude::*;
use indoc::{formatdoc, indoc};
use insta::assert_snapshot;

use uv_test::archive::write_tar_gz;
use uv_test::find_links::FindLinksServer;
use uv_test::packse::{PackseServer, generate_wheel, scenario::Scenario};
use uv_test::{TestContext, uv_snapshot};

fn wheel(context: &TestContext, name: &str, version: &str, tag: &str) -> Result<ChildPath> {
    let links = context.temp_dir.child("links");
    links.create_dir_all()?;
    let (filename, bytes) = generate_wheel(
        &name.parse()?,
        &version.parse()?,
        &[],
        &BTreeMap::new(),
        None,
        tag,
        &[],
    );
    let wheel = links.child(filename);
    wheel.write_binary(&bytes)?;
    Ok(wheel)
}

/// A libc baseline preserves all wheels and hashes, including wheels for newer hosts.
#[test]
fn minimum_libc_retains_locked_wheels() -> Result<()> {
    let scenario = toml::from_str::<Scenario>(indoc! {r#"
        name = "minimum-libc-retains-wheels"

        [root]

        [expected]
        satisfiable = true

        [packages.demo.versions."1.0.0"]
        sdist = false
        wheel_tags = ["py3-none-manylinux_2_17_x86_64", "py3-none-manylinux_2_34_x86_64", "py3-none-musllinux_1_2_x86_64", "py3-none-macosx_11_0_arm64", "py3-none-win_amd64"]
    "#})?;
    let server = PackseServer::from_scenario(&scenario);
    let context = uv_test::test_context!("3.12").with_filters(
        server
            .files()
            .map(|(filename, hash)| (hash.to_owned(), format!("[SHA256:{filename}]"))),
    );
    context
        .temp_dir
        .child("pyproject.toml")
        .write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        preview-features = ["minimum-libc-version"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.31" }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().arg("--index-url").arg(server.index_url()), @"
    exit_code: 0 (success)
    ----- stderr -----
    Resolved 2 packages in [TIME]
    ");
    insta::with_settings!({filters => context.filters()}, {
        assert_snapshot!(context.read("uv.lock"), @r#"
        version = 1
        revision = 3
        requires-python = ">=3.12"
        required-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]

        [options]
        minimum-libc-version = { glibc = "2.31" }
        exclude-newer = "2024-03-25T00:00:00Z"

        [[package]]
        name = "demo"
        version = "1.0.0"
        source = { registry = "http://[LOCALHOST]/simple/" }
        wheels = [
            { url = "http://[LOCALHOST]/files/demo-1.0.0-py3-none-macosx_11_0_arm64.whl", hash = "sha256:[SHA256:demo-1.0.0-py3-none-macosx_11_0_arm64.whl]", upload-time = "2024-03-24T00:00:00Z" },
            { url = "http://[LOCALHOST]/files/demo-1.0.0-py3-none-manylinux_2_17_x86_64.whl", hash = "sha256:[SHA256:demo-1.0.0-py3-none-manylinux_2_17_x86_64.whl]", upload-time = "2024-03-24T00:00:00Z" },
            { url = "http://[LOCALHOST]/files/demo-1.0.0-py3-none-manylinux_2_34_x86_64.whl", hash = "sha256:[SHA256:demo-1.0.0-py3-none-manylinux_2_34_x86_64.whl]", upload-time = "2024-03-24T00:00:00Z" },
            { url = "http://[LOCALHOST]/files/demo-1.0.0-py3-none-musllinux_1_2_x86_64.whl", hash = "sha256:[SHA256:demo-1.0.0-py3-none-musllinux_1_2_x86_64.whl]", upload-time = "2024-03-24T00:00:00Z" },
            { url = "http://[LOCALHOST]/files/demo-1.0.0-py3-none-win_amd64.whl", hash = "sha256:[SHA256:demo-1.0.0-py3-none-win_amd64.whl]", upload-time = "2024-03-24T00:00:00Z" },
        ]

        [[package]]
        name = "project"
        version = "0.1.0"
        source = { virtual = "." }
        dependencies = [
            { name = "demo" },
        ]

        [package.metadata]
        requires-dist = [{ name = "demo" }]
        "#);
    });
    uv_snapshot!(context.filters(), context.lock().arg("--locked").arg("--index-url").arg(server.index_url()), @"
    exit_code: 0 (success)
    ----- stderr -----
    Resolved 2 packages in [TIME]
    ");
    uv_snapshot!(context.filters(), context.export().arg("--frozen"), @r"
    exit_code: 0 (success)
    ----- stdout -----
    # This file was autogenerated by uv via the following command:
    #    uv export --cache-dir [CACHE_DIR] --frozen
    demo==1.0.0 \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-win_amd64.whl] \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-manylinux_2_34_x86_64.whl] \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-musllinux_1_2_x86_64.whl] \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-manylinux_2_17_x86_64.whl] \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-macosx_11_0_arm64.whl]
        # via project
    ");

    uv_snapshot!(context.filters(), context.sync().args(["--frozen", "--python-platform", "x86_64-manylinux_2_31"]), @"
    exit_code: 0 (success)
    ----- stderr -----
    Prepared 1 package in [TIME]
    Installed 1 package in [TIME]
     + demo==1.0.0
    ");
    let wheel_metadata = context.site_packages().join("demo-1.0.0.dist-info/WHEEL");
    assert_snapshot!(fs_err::read_to_string(&wheel_metadata)?, @"
    Wheel-Version: 1.0
    Generator: uv-test
    Root-Is-Purelib: true
    Tag: py3-none-manylinux_2_17_x86_64
    ");

    uv_snapshot!(context.filters(), context.sync().args(["--frozen", "--reinstall", "--python-platform", "x86_64-manylinux_2_34"]), @"
    exit_code: 0 (success)
    ----- stderr -----
    Prepared 1 package in [TIME]
    Uninstalled 1 package in [TIME]
    Installed 1 package in [TIME]
     ~ demo==1.0.0
    ");
    assert_snapshot!(fs_err::read_to_string(&wheel_metadata)?, @"
    Wheel-Version: 1.0
    Generator: uv-test
    Root-Is-Purelib: true
    Tag: py3-none-manylinux_2_34_x86_64
    ");

    uv_snapshot!(context.filters(), context.pip_compile()
        .arg("pyproject.toml")
        .arg("--universal")
        .arg("--generate-hashes")
        .arg("--index-url").arg(server.index_url()), @r"
    exit_code: 0 (success)
    ----- stdout -----
    # This file was autogenerated by uv via the following command:
    #    uv pip compile --cache-dir [CACHE_DIR] pyproject.toml --universal --generate-hashes
    demo==1.0.0 \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-win_amd64.whl] \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-manylinux_2_34_x86_64.whl] \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-musllinux_1_2_x86_64.whl] \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-manylinux_2_17_x86_64.whl] \
        --hash=sha256:[SHA256:demo-1.0.0-py3-none-macosx_11_0_arm64.whl]
        # via project (pyproject.toml)

    ----- stderr -----
    Resolved 1 package in [TIME]
    ");
    Ok(())
}

/// Each configured libc baseline needs coverage; retained wheels for another libc are insufficient.
#[test]
fn minimum_libc_switch_families() -> Result<()> {
    let context = uv_test::test_context!("3.12");
    let filters: Vec<_> = context
        .filters()
        .into_iter()
        .chain([(
            r"\nhint: The resolution failed for an environment that is not the current one[^\n]*",
            "",
        )])
        .collect();
    for (version, tag) in [
        ("1.0.0", "cp312-cp312-manylinux_2_17_x86_64"),
        ("1.0.0", "cp312-cp312-musllinux_1_2_x86_64"),
        ("2.0.0", "cp312-cp312-manylinux_2_17_x86_64"),
        ("2.0.0", "cp312-cp312-musllinux_1_3_x86_64"),
        ("3.0.0", "cp312-cp312-musllinux_1_2_x86_64"),
    ] {
        wheel(&context, "demo", version, tag)?;
    }

    let pyproject_toml = context.temp_dir.child("pyproject.toml");
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.31" }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    ");
    let lock = context.read("uv.lock");
    insta::with_settings!({filters => context.filters()}, {
        assert_snapshot!(lock, @r#"
        version = 1
        revision = 3
        requires-python = ">=3.12"
        resolution-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]
        supported-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]
        required-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]

        [options]
        minimum-libc-version = { glibc = "2.31" }
        exclude-newer = "2024-03-25T00:00:00Z"

        [[package]]
        name = "demo"
        version = "2.0.0"
        source = { registry = "links" }
        wheels = [
            { path = "demo-2.0.0-cp312-cp312-manylinux_2_17_x86_64.whl" },
            { path = "demo-2.0.0-cp312-cp312-musllinux_1_3_x86_64.whl" },
        ]

        [[package]]
        name = "project"
        version = "0.1.0"
        source = { virtual = "." }
        dependencies = [
            { name = "demo" },
        ]

        [package.metadata]
        requires-dist = [{ name = "demo" }]
        "#);
    });

    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.31", musl = "1.2" }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().args(["--offline", "--upgrade"]), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    Updated demo v2.0.0 -> v1.0.0
    ");
    let lock = context.read("uv.lock");
    insta::with_settings!({filters => context.filters()}, {
        assert_snapshot!(lock, @r#"
        version = 1
        revision = 3
        requires-python = ">=3.12"
        resolution-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]
        supported-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]
        required-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]

        [options]
        minimum-libc-version = { glibc = "2.31", musl = "1.2" }
        exclude-newer = "2024-03-25T00:00:00Z"

        [[package]]
        name = "demo"
        version = "1.0.0"
        source = { registry = "links" }
        wheels = [
            { path = "demo-1.0.0-cp312-cp312-manylinux_2_17_x86_64.whl" },
            { path = "demo-1.0.0-cp312-cp312-musllinux_1_2_x86_64.whl" },
        ]

        [[package]]
        name = "project"
        version = "0.1.0"
        source = { virtual = "." }
        dependencies = [
            { name = "demo" },
        ]

        [package.metadata]
        requires-dist = [{ name = "demo" }]
        "#);
    });

    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo>=2"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.31", musl = "1.2" }
    "#})?;
    uv_snapshot!(filters, context.lock().arg("--offline"), @"
    exit_code: 1 (failure)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    error: No solution found when resolving dependencies for split (markers: python_full_version >= '3.12' and platform_machine == 'x86_64' and sys_platform == 'linux')
      cause: Because demo>=2.0.0 has no `platform_machine == 'x86_64' and sys_platform == 'linux'`-compatible wheels and your project depends on demo>=2, we can conclude that your project's requirements are unsatisfiable.
    ");

    // Generic Linux wheels cover both baselines, but must still match the architecture.
    wheel(&context, "generic", "1.0.0", "py3-none-linux_x86_64")?;
    wheel(&context, "generic", "2.0.0", "py3-none-linux_aarch64")?;
    pyproject_toml.write_str(&context.read("pyproject.toml").replace(
        "dependencies = [\"demo>=2\"]",
        "dependencies = [\"generic\"]",
    ))?;
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    Removed demo v1.0.0
    Added generic v1.0.0
    ");
    Ok(())
}

/// Local-version fallback requires coverage at the configured libc baseline.
#[test]
fn minimum_libc_local_version_fallback() -> Result<()> {
    let context = uv_test::test_context!("3.12");
    for (version, tag) in [
        ("1.0.0", "cp312-cp312-manylinux_2_17_x86_64"),
        ("1.0.0", "cp312-cp312-manylinux_2_17_aarch64"),
        ("1.0.0+cpu", "cp312-cp312-manylinux_2_17_x86_64"),
        ("1.0.0+cpu", "cp312-cp312-manylinux_2_34_aarch64"),
    ] {
        wheel(&context, "demo", version, tag)?;
    }
    let pyproject_toml = context.temp_dir.child("pyproject.toml");
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo; sys_platform == 'linux'"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = []
        minimum-libc-version = { glibc = "2.31" }
    "#})?;

    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 3 packages in [TIME]
    ");
    uv_snapshot!(context.filters(), context.export().args(["--frozen", "--no-hashes", "--no-header", "--no-annotate"]), @r"
        exit_code: 0 (success)
        ----- stdout -----
        demo==1.0.0 ; python_full_version < '3.13' and platform_machine == 'aarch64' and platform_python_implementation == 'CPython' and sys_platform == 'linux'
        demo==1.0.0+cpu ; (python_full_version >= '3.13' and sys_platform == 'linux') or (platform_machine != 'aarch64' and sys_platform == 'linux') or (platform_python_implementation != 'CPython' and sys_platform == 'linux')
    ");

    let lock = context.read("uv.lock");
    insta::with_settings!({filters => context.filters()}, {
        assert_snapshot!(lock, @r#"
        version = 1
        revision = 3
        requires-python = ">=3.12"
        resolution-markers = [
            "python_full_version >= '3.13' or platform_machine != 'aarch64' or platform_python_implementation != 'CPython' or sys_platform != 'linux'",
            "python_full_version < '3.13' and platform_machine == 'aarch64' and platform_python_implementation == 'CPython' and sys_platform == 'linux'",
        ]

        [options]
        minimum-libc-version = { glibc = "2.31" }
        exclude-newer = "2024-03-25T00:00:00Z"

        [[package]]
        name = "demo"
        version = "1.0.0"
        source = { registry = "links" }
        resolution-markers = [
            "python_full_version < '3.13' and platform_machine == 'aarch64' and platform_python_implementation == 'CPython' and sys_platform == 'linux'",
        ]
        wheels = [
            { path = "demo-1.0.0-cp312-cp312-manylinux_2_17_aarch64.whl" },
        ]

        [[package]]
        name = "demo"
        version = "1.0.0+cpu"
        source = { registry = "links" }
        resolution-markers = [
            "python_full_version >= '3.13' or platform_machine != 'aarch64' or platform_python_implementation != 'CPython' or sys_platform != 'linux'",
        ]
        wheels = [
            { path = "demo-1.0.0+cpu-cp312-cp312-manylinux_2_17_x86_64.whl" },
            { path = "demo-1.0.0+cpu-cp312-cp312-manylinux_2_34_aarch64.whl" },
        ]

        [[package]]
        name = "project"
        version = "0.1.0"
        source = { virtual = "." }
        dependencies = [
            { name = "demo", version = "1.0.0", source = { registry = "links" }, marker = "python_full_version < '3.13' and platform_machine == 'aarch64' and platform_python_implementation == 'CPython' and sys_platform == 'linux'" },
            { name = "demo", version = "1.0.0+cpu", source = { registry = "links" }, marker = "(python_full_version >= '3.13' and sys_platform == 'linux') or (platform_machine != 'aarch64' and sys_platform == 'linux') or (platform_python_implementation != 'CPython' and sys_platform == 'linux')" },
        ]

        [package.metadata]
        requires-dist = [{ name = "demo", marker = "sys_platform == 'linux'" }]
        "#);
    });
    Ok(())
}

/// Tightening the deployment floor changes the selected version and is recorded in the lock.
#[test]
fn minimum_libc_backtracks_and_invalidates_lock() -> Result<()> {
    let context = uv_test::test_context!("3.12");
    for (version, tag) in [
        ("1.0.0", "cp312-cp312-manylinux_2_17_x86_64"),
        ("2.0.0", "cp312-cp312-manylinux_2_34_x86_64"),
    ] {
        wheel(&context, "demo", version, tag)?;
    }

    let pyproject_toml = context.temp_dir.child("pyproject.toml");
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
    "#})?;
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @r"
        exit_code: 0 (success)
        ----- stderr -----
        Resolved 2 packages in [TIME]
    ");
    let original = context.read("uv.lock");

    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.31" }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().args(["--offline", "--locked"]), @"
    exit_code: 1 (failure)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided.

    hint: To update the lockfile, run `uv lock`.
    ");
    assert_eq!(context.read("uv.lock"), original);
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    Updated demo v2.0.0 -> v1.0.0
    ");
    uv_snapshot!(context.filters(), context.export().args(["--frozen", "--no-hashes", "--no-header", "--no-annotate"]), @"
    exit_code: 0 (success)
    ----- stdout -----
    demo==1.0.0
    ");
    uv_snapshot!(context.filters(), context.pip_compile().args(["pyproject.toml", "--universal", "--offline", "--no-header", "--no-annotate"]), @"
    exit_code: 0 (success)
    ----- stdout -----
    demo==1.0.0

    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 1 package in [TIME]
    ");
    let lock = context.read("uv.lock");
    insta::with_settings!({filters => context.filters()}, {
        assert_snapshot!(lock, @r#"
        version = 1
        revision = 3
        requires-python = ">=3.12"
        required-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]

        [options]
        minimum-libc-version = { glibc = "2.31" }
        exclude-newer = "2024-03-25T00:00:00Z"

        [[package]]
        name = "demo"
        version = "1.0.0"
        source = { registry = "links" }
        wheels = [
            { path = "demo-1.0.0-cp312-cp312-manylinux_2_17_x86_64.whl" },
        ]

        [[package]]
        name = "project"
        version = "0.1.0"
        source = { virtual = "." }
        dependencies = [
            { name = "demo" },
        ]

        [package.metadata]
        requires-dist = [{ name = "demo" }]
        "#);
    });
    uv_snapshot!(context.filters(), context.lock().args(["--offline", "--locked"]), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    ");

    // Changing the floor invalidates the lock even when the selected wheel remains compatible.
    let original = context.read("uv.lock");
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.17" }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().args(["--offline", "--locked"]), @"
    exit_code: 1 (failure)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided.

    hint: To update the lockfile, run `uv lock`.
    ");
    assert_eq!(context.read("uv.lock"), original);

    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
    "#})?;
    uv_snapshot!(context.filters(), context.lock().args(["--offline", "--locked"]), @r"
        exit_code: 1 (failure)
        ----- stderr -----
        Resolved 2 packages in [TIME]
        error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided.

        hint: To update the lockfile, run `uv lock`.
    ");
    assert_eq!(context.read("uv.lock"), original);
    uv_snapshot!(context.filters(), context.pip_compile().args(["pyproject.toml", "--universal", "--offline", "--no-header", "--no-annotate"]), @r"
        exit_code: 0 (success)
        ----- stdout -----
        demo==2.0.0

        ----- stderr -----
        Resolved 1 package in [TIME]
    ");
    Ok(())
}

#[test]
fn minimum_libc_no_compatible_version() -> Result<()> {
    let context = uv_test::test_context!("3.12");
    let filters: Vec<_> = context
        .filters()
        .into_iter()
        .chain([(
            // This hint is only shown when the current platform doesn't match the target.
            r"\nhint: The resolution failed for an environment that is not the current one[^\n]*",
            "",
        )])
        .collect();
    for tag in [
        "cp312-cp312-manylinux_2_34_x86_64",
        "cp312-cp312-musllinux_1_2_x86_64",
    ] {
        wheel(&context, "demo", "2.0.0", tag)?;
    }
    let pyproject_toml = context.temp_dir.child("pyproject.toml");
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.31" }
    "#})?;

    uv_snapshot!(filters, context.lock().arg("--offline"), @"
    exit_code: 1 (failure)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    error: No solution found when resolving dependencies
      cause: Because demo==2.0.0 has no `platform_machine == 'x86_64' and sys_platform == 'linux'`-compatible wheels and only demo==2.0.0 is available, we can conclude that all versions of demo cannot be used.
             And because your project depends on demo, we can conclude that your project's requirements are unsatisfiable.
    ");
    assert!(!context.temp_dir.child("uv.lock").exists());
    // A concrete target uses its platform tags instead of the universal libc baseline.
    uv_snapshot!(context.filters(), context.pip_compile().args(["pyproject.toml", "--python-platform", "x86_64-manylinux_2_34", "--offline", "--no-header", "--no-annotate"]), @"
    exit_code: 0 (success)
    ----- stdout -----
    demo==2.0.0

    ----- stderr -----
    Resolved 1 package in [TIME]
    ");
    Ok(())
}

/// A source distribution remains usable when its wheel requires a newer glibc.
#[test]
fn minimum_libc_allows_sdist_fallback() -> Result<()> {
    let context = uv_test::test_context!("3.12").with_filters([(
        r"\nhint: The resolution failed for an environment that is not the current one[^\n]*"
            .to_string(),
        String::new(),
    )]);
    wheel(
        &context,
        "demo",
        "2.0.0",
        "cp312-cp312-manylinux_2_34_x86_64",
    )?;
    write_tar_gz(
        fs_err::File::create(context.temp_dir.child("links/demo-2.0.0.tar.gz").path())?,
        &[
            (
                "demo-2.0.0/PKG-INFO",
                indoc! {r"
                    Metadata-Version: 2.3
                    Name: demo
                    Version: 2.0.0
                    Requires-Python: >=3.12
                "},
            ),
            (
                "demo-2.0.0/pyproject.toml",
                indoc! {r#"
                    [project]
                    name = "demo"
                    version = "2.0.0"
                    requires-python = ">=3.12"
                    dependencies = []
                "#},
            ),
        ],
    )?;
    let pyproject_toml = context.temp_dir.child("pyproject.toml");
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["demo"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.31" }
    "#})?;

    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    ");
    let lock = context.read("uv.lock");
    insta::with_settings!({filters => context.filters()}, {
        assert_snapshot!(lock, @r#"
        version = 1
        revision = 3
        requires-python = ">=3.12"
        required-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
        ]

        [options]
        minimum-libc-version = { glibc = "2.31" }
        exclude-newer = "2024-03-25T00:00:00Z"

        [[package]]
        name = "demo"
        version = "2.0.0"
        source = { registry = "links" }
        sdist = { path = "demo-2.0.0.tar.gz" }
        wheels = [
            { path = "demo-2.0.0-cp312-cp312-manylinux_2_34_x86_64.whl" },
        ]

        [[package]]
        name = "project"
        version = "0.1.0"
        source = { virtual = "." }
        dependencies = [
            { name = "demo" },
        ]

        [package.metadata]
        requires-dist = [{ name = "demo" }]
        "#);
    });

    // Reconsider the cached flat-index entry when its source distribution cannot be built.
    uv_snapshot!(context.filters(), context.lock().args(["--offline", "--no-build", "--upgrade"]), @"
    exit_code: 1 (failure)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    error: No solution found when resolving dependencies
      cause: Because demo==2.0.0 has no `platform_machine == 'x86_64' and sys_platform == 'linux'`-compatible wheels and only demo==2.0.0 is available, we can conclude that all versions of demo cannot be used.
             And because your project depends on demo, we can conclude that your project's requirements are unsatisfiable.
    ");

    Ok(())
}

#[test]
fn minimum_libc_direct_url() -> Result<()> {
    let context = uv_test::test_context!("3.12").with_filters([(
        r"\nhint: The resolution failed for an environment that is not the current one[^\n]*"
            .to_string(),
        String::new(),
    )]);
    let wheel = wheel(
        &context,
        "demo",
        "2.0.0",
        "cp312-cp312-manylinux_2_34_x86_64",
    )?;
    let server = FindLinksServer::new(context.temp_dir.child("links").path());
    let filename = wheel
        .file_name()
        .context("wheel has no file name")?
        .to_string_lossy();
    let dependency = format!("demo @ {}/{filename}", server.url());
    let pyproject_toml = context.temp_dir.child("pyproject.toml");
    pyproject_toml.write_str(&formatdoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["{dependency}"]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = {{ glibc = "2.31" }}
    "#})?;

    uv_snapshot!(context.filters(), context.lock(), @"
    exit_code: 1 (failure)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    error: No solution found when resolving dependencies
      cause: Because only demo==2.0.0 is available and demo==2.0.0 has no `platform_machine == 'x86_64' and sys_platform == 'linux'`-compatible wheels, we can conclude that all versions of demo cannot be used.
             And because your project depends on demo, we can conclude that your project's requirements are unsatisfiable.
    ");
    assert!(!context.temp_dir.child("uv.lock").exists());

    // Raising the glibc baseline admits the direct wheel.
    pyproject_toml.write_str(&formatdoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["{dependency}"]

        [tool.uv]
        no-index = true
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = {{ glibc = "2.34" }}
    "#})?;
    uv_snapshot!(context.filters(), context.lock(), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 2 packages in [TIME]
    ");

    // Retaining the glibc wheel is not enough to satisfy a musl baseline.
    pyproject_toml.write_str(&formatdoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = ["{dependency}"]

        [tool.uv]
        no-index = true
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = {{ musl = "1.2" }}
    "#})?;
    uv_snapshot!(context.filters(), context.lock(), @"
    exit_code: 1 (failure)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    error: No solution found when resolving dependencies
      cause: Because only demo==2.0.0 is available and demo==2.0.0 has no `platform_machine == 'x86_64' and sys_platform == 'linux'`-compatible wheels, we can conclude that all versions of demo cannot be used.
             And because your project depends on demo, we can conclude that your project's requirements are unsatisfiable.
    ");
    Ok(())
}

/// Every required architecture needs coverage, while unrelated marker branches remain independent.
#[test]
fn minimum_libc_architectures_and_markers() -> Result<()> {
    let context = uv_test::test_context!("3.12");
    for (version, tag) in [
        ("1.0.0", "cp312-cp312-manylinux2014_x86_64"),
        ("1.0.0", "cp312-cp312-manylinux_2_31_aarch64"),
        ("1.0.0", "cp312-cp312-musllinux_1_2_x86_64"),
        ("1.0.0", "cp312-cp312-musllinux_1_2_aarch64"),
        (
            "2.0.0",
            "cp312-cp312-manylinux_2_17_x86_64.manylinux_2_34_aarch64",
        ),
        ("2.0.0", "cp312-cp312-manylinux_2_34_aarch64"),
        ("2.0.0", "cp312-cp312-musllinux_1_2_aarch64"),
        ("2.0.0", "cp312-cp312-macosx_11_0_arm64"),
    ] {
        wheel(&context, "demo", version, tag)?;
    }
    wheel(&context, "windows-only", "1.0.0", "cp312-cp312-win_amd64")?;
    let pyproject_toml = context.temp_dir.child("pyproject.toml");
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = [
            "demo; sys_platform == 'linux'",
            "demo>=2; sys_platform == 'darwin'",
            "windows-only; sys_platform == 'win32'",
        ]

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = [
            "sys_platform == 'linux' and platform_machine == 'x86_64'",
            "sys_platform == 'linux' and platform_machine == 'aarch64'",
        ]
        minimum-libc-version = { glibc = "2.31" }
    "#})?;

    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @"
    exit_code: 0 (success)
    ----- stderr -----
    warning: Setting `minimum-libc-version` is experimental and may change without warning. Pass `--preview-features minimum-libc-version` to disable this warning.
    Resolved 4 packages in [TIME]
    ");
    // The mixed-tag wheel remains eligible for x86_64, but its too-new ARM tag cannot
    // provide coverage. ARM needs the older release.
    uv_snapshot!(context.filters(), context.export().args(["--frozen", "--no-hashes", "--no-header", "--no-annotate"]), @"
    exit_code: 0 (success)
    ----- stdout -----
    demo==1.0.0 ; platform_machine != 'x86_64' and sys_platform == 'linux'
    demo==2.0.0 ; (platform_machine == 'x86_64' and sys_platform == 'linux') or sys_platform == 'darwin'
    windows-only==1.0.0 ; sys_platform == 'win32'
    ");
    let lock = context.read("uv.lock");
    insta::with_settings!({filters => context.filters()}, {
        assert_snapshot!(lock, @r#"
        version = 1
        revision = 3
        requires-python = ">=3.12"
        resolution-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
            "platform_machine != 'x86_64' and sys_platform == 'linux'",
            "sys_platform == 'darwin'",
            "sys_platform != 'darwin' and sys_platform != 'linux'",
        ]
        required-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
            "platform_machine == 'aarch64' and sys_platform == 'linux'",
        ]

        [options]
        minimum-libc-version = { glibc = "2.31" }
        exclude-newer = "2024-03-25T00:00:00Z"

        [[package]]
        name = "demo"
        version = "1.0.0"
        source = { registry = "links" }
        resolution-markers = [
            "platform_machine != 'x86_64' and sys_platform == 'linux'",
        ]
        wheels = [
            { path = "demo-1.0.0-cp312-cp312-manylinux_2_31_aarch64.whl" },
            { path = "demo-1.0.0-cp312-cp312-manylinux2014_x86_64.whl" },
            { path = "demo-1.0.0-cp312-cp312-musllinux_1_2_aarch64.whl" },
            { path = "demo-1.0.0-cp312-cp312-musllinux_1_2_x86_64.whl" },
        ]

        [[package]]
        name = "demo"
        version = "2.0.0"
        source = { registry = "links" }
        resolution-markers = [
            "platform_machine == 'x86_64' and sys_platform == 'linux'",
            "sys_platform == 'darwin'",
        ]
        wheels = [
            { path = "demo-2.0.0-cp312-cp312-macosx_11_0_arm64.whl" },
            { path = "demo-2.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux_2_34_aarch64.whl" },
        ]

        [[package]]
        name = "project"
        version = "0.1.0"
        source = { virtual = "." }
        dependencies = [
            { name = "demo", version = "1.0.0", source = { registry = "links" }, marker = "platform_machine != 'x86_64' and sys_platform == 'linux'" },
            { name = "demo", version = "2.0.0", source = { registry = "links" }, marker = "(platform_machine == 'x86_64' and sys_platform == 'linux') or sys_platform == 'darwin'" },
            { name = "windows-only", marker = "sys_platform == 'win32'" },
        ]

        [package.metadata]
        requires-dist = [
            { name = "demo", marker = "sys_platform == 'darwin'", specifier = ">=2" },
            { name = "demo", marker = "sys_platform == 'linux'" },
            { name = "windows-only", marker = "sys_platform == 'win32'" },
        ]

        [[package]]
        name = "windows-only"
        version = "1.0.0"
        source = { registry = "links" }
        wheels = [
            { path = "windows_only-1.0.0-cp312-cp312-win_amd64.whl" },
        ]
        "#);
    });

    Ok(())
}

#[test]
fn minimum_libc_invalid_configuration() -> Result<()> {
    let context = uv_test::test_context!("3.12");
    let pyproject_toml = context.temp_dir.child("pyproject.toml");
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = []

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
        minimum-libc-version = { glibc = "2.31.1" }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @r#"
    exit_code: 2 (failure)
    ----- stderr -----
    warning: Failed to parse `pyproject.toml` during settings discovery:
      TOML parse error at line 11, column 34
         |
      11 | minimum-libc-version = { glibc = "2.31.1" }
         |                                  ^^^^^^^^
      expected a libc version in the form `<major>.<minor>` (e.g., `2.31` or `1.2`)

    error: Failed to parse: `pyproject.toml`
      cause: TOML parse error at line 11, column 34
                |
             11 | minimum-libc-version = { glibc = "2.31.1" }
                |                                  ^^^^^^^^
             expected a libc version in the form `<major>.<minor>` (e.g., `2.31` or `1.2`)
    "#);

    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = []

        [tool.uv]
        minimum-libc-version = { musl = false }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @"
    exit_code: 2 (failure)
    ----- stderr -----
    warning: Failed to parse `pyproject.toml` during settings discovery:
      TOML parse error at line 8, column 33
        |
      8 | minimum-libc-version = { musl = false }
        |                                 ^^^^^
      invalid type: boolean `false`, expected a libc version string in the form `<major>.<minor>`

    error: Failed to parse: `pyproject.toml`
      cause: TOML parse error at line 8, column 33
               |
             8 | minimum-libc-version = { musl = false }
               |                                 ^^^^^
             invalid type: boolean `false`, expected a libc version string in the form `<major>.<minor>`
    ");

    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = []

        [tool.uv]
        minimum-libc-version = { glibc = 2.31 }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @"
    exit_code: 2 (failure)
    ----- stderr -----
    warning: Failed to parse `pyproject.toml` during settings discovery:
      TOML parse error at line 8, column 34
        |
      8 | minimum-libc-version = { glibc = 2.31 }
        |                                  ^^^^
      invalid type: floating point `2.31`, expected a libc version string in the form `<major>.<minor>`

    error: Failed to parse: `pyproject.toml`
      cause: TOML parse error at line 8, column 34
               |
             8 | minimum-libc-version = { glibc = 2.31 }
               |                                  ^^^^
             invalid type: floating point `2.31`, expected a libc version string in the form `<major>.<minor>`
    ");

    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = []

        [tool.uv]
        minimum-libc-version = { unknown = "1.2" }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @r#"
    exit_code: 2 (failure)
    ----- stderr -----
    warning: Failed to parse `pyproject.toml` during settings discovery:
      TOML parse error at line 8, column 26
        |
      8 | minimum-libc-version = { unknown = "1.2" }
        |                          ^^^^^^^
      unknown field `unknown`, expected `glibc` or `musl`

    error: Failed to parse: `pyproject.toml`
      cause: TOML parse error at line 8, column 26
               |
             8 | minimum-libc-version = { unknown = "1.2" }
               |                          ^^^^^^^
             unknown field `unknown`, expected `glibc` or `musl`
    "#);

    // Like required-environments, the minimum libc version is a project-only setting.
    pyproject_toml.write_str(indoc! {r#"
        [project]
        name = "project"
        version = "0.1.0"
        requires-python = ">=3.12"
        dependencies = []

        [tool.uv]
        no-index = true
        find-links = ["links"]
        required-environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
    "#})?;
    context.temp_dir.child("uv.toml").write_str(indoc! {r#"
        minimum-libc-version = { glibc = "2.31" }
    "#})?;
    uv_snapshot!(context.filters(), context.lock().arg("--offline"), @r"
        exit_code: 2 (failure)
        ----- stderr -----
        warning: Found both a `uv.toml` file and a `[tool.uv]` section in an adjacent `pyproject.toml`. The following fields from `[tool.uv]` will be ignored in favor of the `uv.toml` file:
        - no-index
        - find-links
        error: Failed to parse: `uv.toml`. The `minimum-libc-version` field is not allowed in a `uv.toml` file. `minimum-libc-version` is only applicable in the context of a project, and should be placed in a `pyproject.toml` file instead.
    ");
    Ok(())
}
