[alias]
dev = "run --package uv-dev --features dev"

[env]
# In jemalloc 5.3.1, this was turned on by default but increased peak RSS by ~3% in uv benchmarks
# without a measurable performance improvement, so we turn it back off.
JEMALLOC_SYS_WITH_MALLOC_CONF = "disable_large_size_classes:false"

# statically link the C runtime so the executable does not depend on
# that shared/dynamic library.
#
# See: https://github.com/astral-sh/ruff/issues/11503
[target.'cfg(all(target_env = "msvc", target_os = "windows"))']
rustflags = ["-C", "target-feature=+crt-static"]
