[package]
name = "uv-python-context"
version = "0.0.90"
description = "This is an internal component crate of uv"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
doctest = false
test = false

[lints]
workspace = true

[dependencies]
uv-cache = { workspace = true }
uv-client = { workspace = true }
uv-command-support = { workspace = true }
uv-configuration = { workspace = true }
uv-distribution-types = { workspace = true }
uv-errors = { workspace = true }
uv-fs = { workspace = true }
uv-pep440 = { workspace = true }
uv-python = { workspace = true }
uv-scripts = { workspace = true }
uv-settings = { workspace = true }
uv-warnings = { workspace = true }
uv-workspace = { workspace = true }

indicatif = { workspace = true }
itertools = { workspace = true }
owo-colors = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
