# Dependency metadata from https://github.com/willmcgugan/rich-cli/blob/2577b1b8a113c367ed4b6fcf6dfce4e86520464f/pyproject.toml

[project]
name = "rich-cli"
version = "1.8.1"
requires-python = ">=3.9"
dependencies = [
    "rich (>=12.4.0,<13.0.0)",
    "click (>=8.0.0,<9.0.0)",
    "requests (>=2.0.0,<3.0.0)",
    "textual (>=0.1.18,<0.2.0)",
    "rich-rst (>=1.1.7,<2.0.0)",
]

[dependency-groups]
dev = [
    "black==22.3.0",
    "mypy==0.942",
]

[build-system]
requires = [
    "poetry-core>=2.0.0,<3.0.0",
]
build-backend = "poetry.core.masonry.api"
