use std::io::Write as _;
use std::process::{Command, Stdio};

use tempfile::tempdir;
use uv_python_bytecode::{CPYTHON_TARGET, compile, compile_to_pyc};

const CPYTHON_MARSHAL: &str = "import marshal, sys; code = compile(sys.stdin.read(), sys.argv[1], 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))";

fn python_3145() -> Option<String> {
    let configured = std::env::var("UV_PYTHON_BYTECODE_TEST_PYTHON").ok();
    let executable = configured.as_deref().unwrap_or("python3.14");
    let version = CPYTHON_TARGET.version_string();
    let magic = CPYTHON_TARGET.magic_hex();
    let output = Command::new(executable)
        .args([
            "-c",
            "import importlib.util, sys; expected = tuple(map(int, sys.argv[2].split('.'))); actual = sys.version_info[:3]; magic = importlib.util.MAGIC_NUMBER.hex(); ok = sys.implementation.name == sys.argv[1] and actual == expected and magic == sys.argv[3]; print(f'{sys.implementation.name} {'.'.join(map(str, actual))} magic {magic}', file=sys.stderr); raise SystemExit(not ok)",
            CPYTHON_TARGET.implementation,
            version.as_str(),
            magic.as_str(),
        ])
        .output()
        .ok()?;
    if output.status.success() {
        return Some(executable.to_string());
    }
    assert!(
        configured.is_none(),
        "UV_PYTHON_BYTECODE_TEST_PYTHON must name CPython {} with magic {}: {}",
        version,
        magic,
        String::from_utf8_lossy(&output.stderr).trim()
    );
    None
}

pub(crate) fn assert_matches_cpython_marshal(source: &str, filename: &str) {
    let Some(python) = python_3145() else {
        return;
    };
    let expected = Command::new(python)
        .args(["-c", CPYTHON_MARSHAL, filename])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .and_then(|mut child| {
            child.stdin.take().unwrap().write_all(source.as_bytes())?;
            child.wait_with_output()
        })
        .unwrap();
    assert!(expected.status.success());
    assert_eq!(
        compile(source, filename).unwrap().marshal(),
        expected.stdout
    );
}

pub(crate) fn assert_executes(source: &str, expected: &str) {
    let Some(python) = python_3145() else {
        return;
    };
    let temporary = tempdir().unwrap();
    let pyc_path = temporary.path().join("program.pyc");
    let pyc = compile_to_pyc(source, "program.py", 0).unwrap();
    fs_err::write(&pyc_path, pyc).unwrap();

    let output = Command::new(python).arg(&pyc_path).output().unwrap();
    assert!(
        output.status.success(),
        "generated bytecode failed:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(String::from_utf8(output.stdout).unwrap(), expected);
}
