[project]
name = "zulip-server"
version = "0.1.0"
requires-python = ">=3.10"

[dependency-groups]
prod = [
    "django[argon2]==5.2.*",
    "asgiref",
    "typing-extensions",
    "jinja2",
    "markdown",
    "pygments",
    "jsx-lexer",
    "uri-template",
    "regex",
    "ipython<9",
    "pyvips",
    "boto3",
    "mypy-boto3-s3",
    "mypy-boto3-ses",
    "mypy-boto3-sns",
    "mypy-boto3-sqs",
    "defusedxml",
    "django-bitfield",
    "firebase-admin",
    "html2text",
    "css-inline",
    "pyjwt",
    "pika",
    "psycopg2",
    "python-binary-memcached",
    "redis",
    "tornado",
    "orjson",
    "aioapns",
    "polib",
    "virtualenv-clone",
    "beautifulsoup4",
    "python-magic",
    "zulip",
    "zulip-bots",
    "dnspython",
    "social-auth-app-django",
    "social-auth-core[saml]",
    "python3-saml",
    "cryptography",
    "lxml",
    "django-two-factor-auth[call,phonenumberslite,sms]",
    "stripe",
    "disposable-email-domains",
    "idna",
    "jsonref",
    "pyahocorasick",
    "decorator",
    "zxcvbn",
    "requests[security]",
    "requests-oauthlib",
    "openapi-core>=0.23.1",
    "sentry-sdk",
    "tlds",
    "pyuca",
    "tenacity",
    "pymongo",
    "python-bsonstream>=0.1.4",
    "google-re2",
    "django-cte",
    "django-scim2",
    "pybreaker",
    "django-stubs-ext",
    "pydantic",
    "annotated-types",
    "openai",
    "prometheus-client",
    "altcha",
    "aiosmtpd>=1.4.6",
    "pydantic-partials",
    "pynacl",
    "chardet",
    "zstd",
    "backports-datetime-fromisoformat; python_version < '3.11'",
    "ua-parser[regex]>=1.0.2",
]
docs = [
    "sphinx<8.2",
    "sphinx-rtd-theme",
    "sphinx-design<0.7",
    "sphinx-copybutton",
    "myst-parser",
    "markdown-it-py<4",
]
release-tools = [
    "PyGithub",
    "requests",
    "typer",
]
dev = [
    { include-group = "prod" },
    { include-group = "docs" },
    { include-group = "release-tools" },
    "moto[s3]",
    "aiohttp",
    "scrapy",
    "coverage",
    "responses",
    "line-profiler",
    "black",
    "ruff",
    "pyasyncore",
    "tblib",
    "gitlint-core",
    "snakeviz",
    "python-digitalocean",
    "mypy[faster-cache]",
    "boto3-stubs[s3,ses,sns,sqs]",
    "django-stubs",
    "google-re2-stubs",
    "lxml-stubs",
    "types-beautifulsoup4",
    "types-boto",
    "types-decorator",
    "types-defusedxml",
    "types-jsonschema",
    "types-Markdown",
    "types-oauthlib",
    "types-polib",
    "types-pika",
    "types-psycopg2",
    "types-Pygments",
    "types-pyOpenSSL",
    "types-PyYAML",
    "types-redis",
    "types-regex",
    "types-requests",
    "types-requests-oauthlib",
    "types-uwsgi",
    "types-zstd",
    "types-zxcvbn",
    "python-debian",
    "semgrep<1.80.0",
    "natsort",
    "codespell",
    "time-machine",
]
