//! Fast, unique ID generation, with a focus on small string representations.
//!
//! This crate provides a nanoid-style ID generator, but with IDs of length 16
//! instead of 21. We use the same 64-character alphabet as nanoid,
//! which means that our IDs have 96 bits of entropy.
//!
//! The `serde` feature enables serialization and deserialization of IDs as strings.

use std::fmt;
use std::ops::Deref;

use rand::RngCore as _;

const ALPHABET: [u8; 64] = [
    b'_', b'-', b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'a', b'b', b'c', b'd',
    b'e', b'f', b'g', b'h', b'i', b'j', b'k', b'l', b'm', b'n', b'o', b'p', b'q', b'r', b's', b't',
    b'u', b'v', b'w', b'x', b'y', b'z', b'A', b'B', b'C', b'D', b'E', b'F', b'G', b'H', b'I', b'J',
    b'K', b'L', b'M', b'N', b'O', b'P', b'Q', b'R', b'S', b'T', b'U', b'V', b'W', b'X', b'Y', b'Z',
];
const MASK: u8 = 63;

/// A unique identifier generated by this crate.
///
/// This newtype asserts the use of a CSPRNG; only construct via [`secure`].
#[derive(Copy, Clone, PartialEq, Eq, Hash)]
pub struct SecureId([u8; 16]);

impl Deref for SecureId {
    type Target = str;

    #[inline]
    fn deref(&self) -> &str {
        // SAFETY: `SecureId` is only constructed via `secure()`, whose
        // bytes are always ASCII via `reduce()`.
        #[allow(unsafe_code)]
        unsafe {
            std::str::from_utf8_unchecked(&self.0)
        }
    }
}

impl fmt::Debug for SecureId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("SecureId").field(&&**self).finish()
    }
}

#[cfg(feature = "serde")]
impl serde::Serialize for SecureId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        // Serialize as a string.
        self.deref().serialize(serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for SecureId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        use std::borrow::Cow;
        let s = <Cow<'_, str>>::deserialize(deserializer)?;

        s.as_bytes()
            .as_array()
            .copied()
            .filter(|bytes| bytes.iter().all(|byte| ALPHABET.contains(byte)))
            .map(Self)
            .ok_or_else(|| {
                serde::de::Error::custom(format!("invalid ID: {s:?} (must be 16 ID characters)"))
            })
    }
}

/// A unique identifier generated by this crate.
///
/// This newtype asserts the use of a non-CSPRNG; only construct via [`insecure`].
#[derive(Copy, Clone, PartialEq, Eq, Hash)]
pub struct InsecureId([u8; 16]);

impl Deref for InsecureId {
    type Target = str;

    #[inline]
    fn deref(&self) -> &str {
        // SAFETY: `InsecureId` is only constructed via `insecure()`, whose bytes
        // are always ASCII via `reduce()`.
        #[allow(unsafe_code)]
        unsafe {
            std::str::from_utf8_unchecked(&self.0)
        }
    }
}

impl fmt::Debug for InsecureId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("InsecureId").field(&&**self).finish()
    }
}

#[cfg(feature = "serde")]
impl serde::Serialize for InsecureId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        // Serialize as a string.
        self.deref().serialize(serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for InsecureId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        use std::borrow::Cow;
        let s = <Cow<'_, str>>::deserialize(deserializer)?;

        s.as_bytes()
            .as_array()
            .copied()
            .filter(|bytes| bytes.iter().all(|byte| ALPHABET.contains(byte)))
            .map(Self)
            .ok_or_else(|| {
                serde::de::Error::custom(format!("invalid ID: {s:?} (must be 16 ID characters)"))
            })
    }
}

pub fn secure() -> SecureId {
    let mut raw = [0u8; 16];
    let mut rng = rand::rng();
    rng.fill_bytes(raw.as_mut());
    SecureId(reduce(&raw))
}

pub fn insecure() -> InsecureId {
    let mut raw = [0u8; 16];
    fastrand::fill(&mut raw);
    InsecureId(reduce(&raw))
}

/// Reduce a 16-byte array of random bytes to a 16-byte array of ASCII characters in our ID alphabet.
fn reduce(raw: &[u8; 16]) -> [u8; 16] {
    raw.map(|byte| ALPHABET[(byte & MASK) as usize])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_reduce_kat() {
        for (raw, expected) in [
            ([0u8; 16], "________________"),
            ([255u8; 16], "ZZZZZZZZZZZZZZZZ"),
            (
                [
                    0x00, 0x41, 0x80, 0xc1, 0x00, 0x41, 0x80, 0xc1, 0x00, 0x41, 0x80, 0xc1, 0x00,
                    0x41, 0x80, 0xc1,
                ],
                "_-_-_-_-_-_-_-_-",
            ),
            (
                [
                    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
                    0x0d, 0x0e, 0x0f,
                ],
                "_-0123456789abcd",
            ),
        ] {
            let bytes = reduce(&raw);
            let actual = std::str::from_utf8(&bytes).expect("reduce produces ASCII");
            assert_eq!(actual, expected, "reduce({raw:?}) should be {expected}");
        }
    }

    #[test]
    fn test_secure() {
        let id = secure();
        assert_eq!(id.len(), 16);
        assert!(id.bytes().all(|byte| ALPHABET.contains(&byte)));
    }

    #[test]
    fn test_insecure() {
        let id = insecure();
        assert_eq!(id.len(), 16);
        assert!(id.bytes().all(|byte| ALPHABET.contains(&byte)));
    }

    #[cfg(feature = "serde")]
    mod serde {
        use super::*;

        #[test]
        fn round_trip() {
            let id = secure();
            let json = serde_json::to_string(&id).unwrap();
            let parsed: SecureId = serde_json::from_str(&json).unwrap();
            assert_eq!(id, parsed);

            let id = insecure();
            let json = serde_json::to_string(&id).unwrap();
            let parsed: InsecureId = serde_json::from_str(&json).unwrap();
            assert_eq!(id, parsed);
        }

        #[test]
        fn rejects_wrong_length() {
            for tc in ["\"\"", "\"short\"", "\"0123456789abcdefg\""] {
                assert!(
                    serde_json::from_str::<SecureId>(tc).is_err(),
                    "should reject {tc}"
                );
                assert!(
                    serde_json::from_str::<InsecureId>(tc).is_err(),
                    "should reject {tc}"
                );
            }
        }

        #[test]
        fn rejects_wrong_alphabet() {
            for tc in ["\"0123456789abcde!\"", "\"0123456789abcdeé\""] {
                assert!(
                    serde_json::from_str::<SecureId>(tc).is_err(),
                    "should reject {tc}"
                );
                assert!(
                    serde_json::from_str::<InsecureId>(tc).is_err(),
                    "should reject {tc}"
                );
            }
        }
    }
}
