[project]
name = "pyx-member-35"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "email-validator==2.3.0",
    "msgspec==0.21.1",
    "packaging==26.0",
    "rfc3986==2.0.0",
    "trove-classifiers==2026.1.14.14",
    "urllib3==2.7.0",
    "pyx-member-23",
]

[dependency-groups]
dev = [
    "deptry==0.25.1",
    "ruff==0.15.18",
    "ty==0.0.51",
]
