[project]
name = "pyx-member-09"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "msgspec==0.21.1",
    "pyx-member-04",
    "pyx-member-23",
    "redis==7.4.0",
]

[project.optional-dependencies]
aws = [
    "boto3[crt]==1.42.88",
]

[dependency-groups]
dev = [
    "deptry==0.25.1",
    "inline-snapshot==0.32.6",
    "pytest==9.0.3",
    "pytest-asyncio==1.3.0",
    "pytest-randomly==4.0.1",
    "pyx-member-33",
    "ruff==0.15.18",
    "ty==0.0.51",
]
