//! Compile Python source to CPython bytecode without starting a Python interpreter.
//!
//! This crate currently targets CPython 3.14 exclusively. The bytecode, code object,
//! marshal, and `.pyc` formats are all implementation details that can change between
//! Python minor versions, so future targets should be implemented as separate backends.

mod assembler;
mod compiler;
mod marshal;

use std::error::Error;
use std::fmt;

use compiler::{CodeObject, Compiler};

/// CPython 3.14's bytecode and `.pyc` magic number.
pub const PYTHON_314_MAGIC_NUMBER: [u8; 4] = [0x2b, 0x0e, 0x0d, 0x0a];

/// A compiled CPython 3.14 module code object.
#[derive(Clone, Debug)]
pub struct CompiledModule {
    code: CodeObject,
}

impl CompiledModule {
    /// Return the module's raw CPython instruction stream.
    pub fn bytecode(&self) -> &[u8] {
        &self.code.bytecode
    }

    /// Marshal the module code object using CPython 3.14's format.
    pub fn marshal(&self) -> Vec<u8> {
        marshal::encode_code(&self.code)
    }

    /// Build a timestamp-invalidated CPython 3.14 `.pyc` file.
    ///
    /// `source_mtime` is the source file's modification time in whole seconds since the
    /// Unix epoch. `source_size` is the source file's byte length, truncated to 32 bits as
    /// required by CPython's cache format.
    pub fn to_timestamp_pyc(&self, source_mtime: u32, source_size: u32) -> Vec<u8> {
        let marshalled = self.marshal();
        let mut output = Vec::with_capacity(16 + marshalled.len());
        output.extend_from_slice(&PYTHON_314_MAGIC_NUMBER);
        output.extend_from_slice(&0_u32.to_le_bytes());
        output.extend_from_slice(&source_mtime.to_le_bytes());
        output.extend_from_slice(&source_size.to_le_bytes());
        output.extend_from_slice(&marshalled);
        output
    }
}

/// A source parsing or bytecode generation error.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CompileError {
    /// Ruff rejected the Python source.
    Parse(String),
    /// The source uses valid Python syntax that this backend does not support yet.
    Unsupported(String),
    /// The compiler violated one of its own invariants.
    Internal(String),
}

impl fmt::Display for CompileError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Parse(message) => write!(formatter, "failed to parse Python source: {message}"),
            Self::Unsupported(message) => formatter.write_str(message),
            Self::Internal(message) => write!(formatter, "internal compiler error: {message}"),
        }
    }
}

impl Error for CompileError {}

/// Compile a Python module for CPython 3.14.
pub fn compile(source: &str, filename: &str) -> Result<CompiledModule, CompileError> {
    let normalized;
    let source = if source.contains('\r') {
        normalized = source.replace("\r\n", "\n").replace('\r', "\n");
        normalized.as_str()
    } else {
        source
    };
    let source = source.strip_prefix('\u{feff}').unwrap_or(source);
    let parsed = ruff_python_parser::parse_module(source)
        .map_err(|error| CompileError::Parse(error.to_string()))?;
    let code = Compiler::module(filename, source).compile_module(parsed.suite())?;
    Ok(CompiledModule { code })
}

/// Compile a Python module directly to a timestamp-invalidated CPython 3.14 `.pyc` file.
pub fn compile_to_pyc(
    source: &str,
    filename: &str,
    source_mtime: u32,
) -> Result<Vec<u8>, CompileError> {
    let source_size = u32::try_from(source.len()).map_err(|_| {
        CompileError::Unsupported("Python source exceeds the 4 GiB `.pyc` limit".to_string())
    })?;
    Ok(compile(source, filename)?.to_timestamp_pyc(source_mtime, source_size))
}

#[cfg(test)]
mod tests {
    use std::fmt::Write as _;
    use std::io::Write as _;
    use std::process::{Command, Stdio};

    use tempfile::tempdir;

    use super::{PYTHON_314_MAGIC_NUMBER, compile, compile_to_pyc};

    fn python_314() -> Option<String> {
        let executable = "python3";
        let status = Command::new(executable)
            .args([
                "-c",
                "import sys; raise SystemExit(sys.version_info[:2] != (3, 14))",
            ])
            .status()
            .ok()?;
        status.success().then(|| executable.to_string())
    }

    fn execute(source: &str) -> Option<String> {
        let python = python_314()?;
        let temporary = tempdir().unwrap();
        let pyc_path = temporary.path().join("program.pyc");
        let pyc = compile_to_pyc(source, "program.py", 0).unwrap();
        fs_err::write(&pyc_path, pyc).unwrap();

        let output = Command::new(python).arg(&pyc_path).output().unwrap();
        assert!(
            output.status.success(),
            "generated bytecode failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
        Some(String::from_utf8(output.stdout).unwrap())
    }

    #[test]
    fn emits_a_python_314_pyc_header() {
        let pyc = compile_to_pyc("answer = 42\n", "answer.py", 123).unwrap();
        assert_eq!(&pyc[..4], &PYTHON_314_MAGIC_NUMBER);
        assert_eq!(&pyc[4..8], &0_u32.to_le_bytes());
        assert_eq!(&pyc[8..12], &123_u32.to_le_bytes());
        assert_eq!(&pyc[12..16], &12_u32.to_le_bytes());
    }

    #[test]
    fn matches_cpython_marshal_for_an_empty_module() {
        let Some(python) = python_314() else {
            return;
        };
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile('', 'empty.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .output()
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(compile("", "empty.py").unwrap().marshal(), expected.stdout);
    }

    #[test]
    fn matches_cpython_marshal_for_a_module_containing_only_global_statements() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "global x\nglobal x, y, z\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'global.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "global.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_when_a_match_case_ends_in_a_constant_expression() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "match foo:\n    case foo_bar: ...\nmatch foo:\n    case _: ...\nmatch 1:\n    case _ if (True): ...\nmatch (1, 2):\n    case _: ...\nmatch subject:\n    case [a, b]: ...\n    case (a, b): ...\nmatch value:\n    case 1:\n        h(x)\n    case _:\n        ...\ndef terminal_try_star():\n    try:\n        assigned = 1\n    except* ValueError:\n        assigned = 2\ntry: ...\nexcept* ValueError: ...\nraise terminal\nmatch subject:\n    case unreachable_capture:\n        pass\n[temporary for temporary in values]\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'match.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "match.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_pass_only_try_else_finally() {
        let Some(python) = python_314() else {
            return;
        };
        let source =
            "try:\n    foo()\nexcept Exception:\n    pass\nelse:\n    pass\nfinally:\n    pass\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'try.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "try.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_multiple_exception_group_handlers() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "try:\n    body()\nexcept* ValueError:\n    first()\nexcept* TypeError:\n    second()\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'try_star.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "try_star.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_a_return_from_an_exception_handler() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "def f():\n    value = source()\n    try:\n        raise ValueError\n    except ValueError:\n        return value\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'handler_return.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "handler_return.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_optimized_boolean_operands() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "if a and f() and False and g():\n    pass\na or \"\" or True\na or () or True\na and \"value\" and False\n0 if a or [1] or True or [2] else 1\nif (\n    f()\n    is None\n):\n    pass\nif g() is not None:\n    pass\nx\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'bool.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "bool.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_branch_result_ownership() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "def ternary(name, suffix):\n    return name[:-len(suffix)] if name.endswith(suffix) else name\n\ndef simple(condition, left, right):\n    return left if condition else right\n\ndef boolean(left, right):\n    return left or right\n\ndef nested(condition, name):\n    return name.upper() if condition else name\n\ndef nested_boolean(left, middle, right):\n    return (left and middle) or right, (left or middle) and right\n\ndef folded_annotation(arg: 2 or None | int):\n    pass\n\nlambda_conditional = lambda condition, left, right: left if condition else right\nlambda_boolean = lambda left, right: left or right\nmodule_boolean = (left and middle) or right\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'ownership.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "ownership.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_local_borrowing_across_exception_regions() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "def try_return():\n    try:\n        value = process()\n        return value\n    except ValueError:\n        pass\n\ndef with_return(manager):\n    with manager:\n        return 1\n\ndef match_subject(provided):\n    match provided:\n        case True:\n            return captured\n\ndef comprehension(collection):\n    return [element for element in collection if element is not None]\n\ndef repeated_checked_load():\n    value = value[value.attribute == 'key']\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'borrowing.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "borrowing.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_a_constant_true_comprehension_filter() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "value: int\n[x for x in values if True]\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'comprehension.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "comprehension.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_a_redundant_nop_after_annotation_setup() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "()\nvalue: int\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'annotation.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "annotation.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_an_inline_constant_with_body() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "import io\nwith (\n    io  # comment\n    .open('file.txt') as file\n): ...\nwith manager:\n    while condition:\n        body()\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'with.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "with.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_a_tuple_containing_a_constant_slice() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "constant = lambda value: value[:, 1]\ndynamic = lambda value: value[::-1]\nwith_defaults = lambda value=1, other=2: value\nstring_slice = 'héllo'[1:4]\nstepped_string_slice = 'abcdef'[1:5:2]\nboolean_slice = 'abc'[False:True:True]\nbytes_slice = b'prefix'[2:]\ntuple_slice = (1, 2, 3)[1:]\nnegative_slice = 'abc'[:-1]\nstring_index = 'héllo'[1]\nfstring_index = f'abc'[0]\nbytes_index = b'prefix'[-1]\ntuple_index = (1, 2, 3)[-2]\ndynamic_list_index = [1, 2, 3][0]\nmember = item in [1, 2]\ndouble_negation = not not item\n5.0 ** 5.0\nTrue ** True\nFalse ** False\n() << 0 ** 99999999999999999999999999\n1 - 2\ninverted = ~1\nnegative_zero = -0000\nmixed = 1 + 2.5\nassert (False, 'x')\nassert (False,)\nassert ()\nassert True\npacked = fn('User', **{'name': str})\nunicode_keyword = fn(café=1)\nhuge = -999999999999999999999999999999999999999999\nadjacent = ('' f'prefix {item}')\nleft if condition else right\n'%s' % ('value',)\nif (1, 2):\n    pass\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'example.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::null())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "example.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn matches_cpython_marshal_for_lambda_edge_cases() {
        let Some(python) = python_314() else {
            return;
        };
        let source = "from __future__ import barry_as_FLUFL, generator_stop, print_function\nsimple = lambda: (yield None)\nyield_value = lambda value: (yield value)\ndelegating = lambda: (yield from source())\ndef eliminated():\n    while False:\n        value = lambda: missing\ndef   trailing_semicolon():\n    value = 1 \\\n        ;\ndef trailing_semicolon_try():\n    try:\n        value = 1;\n    except ValueError:\n        pass;\ndef overridden_return():\n    try:\n        return 1\n    finally:\n        return 2\ndef overridden_handler_return():\n    try:\n        pass\n    except:\n        return 1\n    finally:\n        return 2\ndef empty_try_else():\n    try:\n        pass\n    except:\n        return 1\n    else:\n        return 2\ndef dead_loop_return(value):\n    while value > 0:\n        break\n        return 1\ndef return_inside_with():\n    with manager:\n        return 1\nasync  def terminal_async_comprehension():\n    if test:\n        values = [value async for value in source]\n";
        let expected = Command::new(python)
            .args([
                "-c",
                "import marshal, sys; code = compile(sys.stdin.read(), 'example.py', 'exec', dont_inherit=True, optimize=0); sys.stdout.buffer.write(marshal.dumps(code))",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                child.stdin.as_mut().unwrap().write_all(source.as_bytes())?;
                child.wait_with_output()
            })
            .unwrap();
        assert!(expected.status.success());
        assert_eq!(
            compile(source, "example.py").unwrap().marshal(),
            expected.stdout
        );
    }

    #[test]
    fn executes_arithmetic_names_and_calls() {
        let Some(output) = execute("answer = 6 * 7\nprint(answer)\n") else {
            return;
        };
        assert_eq!(output, "42\n");
    }

    #[test]
    fn executes_control_flow() {
        let source = r#"
x = 3
total = 0
while x:
    total += x
    x -= 1

if total == 6:
    print("ok")
else:
    print("bad")
"#;
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "ok\n");
    }

    #[test]
    fn executes_simple_functions() {
        let source = r"
def add(left, right):
    result = left + right
    return result

print(add(20, 22))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "42\n");
    }

    #[test]
    fn executes_literals_and_collections() {
        let source = r#"
values = [1, 2, 3]
pair = ("answer", 42)
mapping = {"answer": 42}
print(values[1], pair[0], mapping["answer"])
"#;
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "2 answer 42\n");
    }

    #[test]
    fn executes_short_circuit_expressions() {
        let source = r"
zero = 0
one = 1
print(zero and missing, one or missing, 1 if zero else 2, not zero)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "0 1 2 True\n");
    }

    #[test]
    fn executes_break_continue_and_while_else() {
        let source = r"
x = 4
total = 0
while x:
    x -= 1
    if x == 2:
        continue
    if x == 0:
        break
    total += x
else:
    total = 999
print(total)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "4\n");
    }

    #[test]
    fn executes_function_globals_and_docstrings() {
        let source = r#"
base = 40
def answer(offset):
    "answer docs"
    return base + offset

print(answer(2), answer.__doc__)
"#;
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "42 answer docs\n");
    }

    #[test]
    fn executes_extended_arguments_and_large_integers() {
        let mut source = String::from("flag = False\nif flag:\n");
        for index in 0..300 {
            writeln!(&mut source, "    value_{index} = {index}").unwrap();
        }
        source.push_str("else:\n    value_299 = 9223372036854775808\nprint(value_299)\n");

        let Some(output) = execute(&source) else {
            return;
        };
        assert_eq!(output, "9223372036854775808\n");
    }

    #[test]
    fn executes_for_loops_imports_and_globals() {
        let source = r"
import math as mathematics
from operator import add as plus

total = 0
for value in [1, 2, 3]:
    if value == 2:
        continue
    total = plus(total, value)
else:
    total += int(mathematics.sqrt(4))

def bump():
    global total
    total += 1

bump()
print(total)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "7\n");
    }

    #[test]
    fn executes_unpacking_stores_and_deletes() {
        let source = r"
from types import SimpleNamespace

box = SimpleNamespace(value=1)
box.value += 4
values = [10, 20, 30]
values[1] += 2
head, *middle, tail = values
box.extra = head + tail
del values[0]
del box.extra
print(box.value, values, head, middle, tail, hasattr(box, 'extra'))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "5 [22, 30] 10 [22] 30 False\n");
    }

    #[test]
    fn executes_starred_calls_collections_slices_and_comparisons() {
        let source = r"
def combine(a, b, c):
    return a + b + c

args = (1, 2)
keywords = {'c': 3}
values = [0, *args, 3]
mapping = {'a': 1, **{'b': 2}}
result = combine(*args, **keywords)
print(result, values[1:3], mapping, 0 < result < 10, (captured := result))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "6 [1, 2] {'a': 1, 'b': 2} True 6\n");
    }

    #[test]
    fn executes_full_function_signatures_and_decorators() {
        let source = r"
def identity(function):
    return function

@identity
def combine(a, b=2, *args, c=3, **kwargs):
    return a + b + sum(args) + c + kwargs['d']

print(combine(1, 4, 5, 6, c=7, d=8))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "31\n");
    }

    #[test]
    fn executes_lambdas_with_full_signatures() {
        let source = r"
combine = lambda a, b=2, *args, c=3, **kwargs: a + b + sum(args) + c + kwargs['d']
print(combine(1, 4, 5, 6, c=7, d=8))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "31\n");
    }

    #[test]
    fn executes_nested_closures() {
        let source = r"
def outer(x):
    y = 2
    def middle(z):
        def inner():
            return x + y + z
        return inner
    return middle

print(outer(1)(3)())
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "6\n");
    }

    #[test]
    fn executes_nonlocal_assignments() {
        let source = r"
def counter():
    value = 0
    def bump():
        nonlocal value
        value += 1
        return value
    return bump

bump = counter()
print(bump(), bump())
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "1 2\n");
    }

    #[test]
    fn executes_fstrings_and_arbitrary_precision_integers() {
        let source = r#"
value = 1234567890123456789012345678901234567890
width = 6
print(f"value={value!r} suffix={value:0{width}d}")
print(f"{width=}")
"#;
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(
            output,
            "value=1234567890123456789012345678901234567890 suffix=1234567890123456789012345678901234567890\nwidth=6\n"
        );
    }

    #[test]
    fn executes_classes_bases_decorators_and_methods() {
        let source = r"
def identity(value):
    return value

class Base:
    base = 40

@identity
class Answer(Base):
    offset = 2
    def value(self):
        return self.base + self.offset

print(Answer().value(), Answer.__firstlineno__, Answer.__static_attributes__)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "42 8 ()\n");
    }

    #[test]
    fn executes_deferred_function_annotations() {
        let source = r"
def concrete(value: int) -> str:
    return str(value)

print(concrete.__annotations__)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(
            output,
            "{'value': <class 'int'>, 'return': <class 'str'>}\n"
        );

        let source = r"
from __future__ import annotations

def deferred(value: list[int]) -> str:
    return str(value)

print(deferred.__annotations__)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "{'value': 'list[int]', 'return': 'str'}\n");
    }

    #[test]
    fn executes_future_module_annotations() {
        let source = r"
from __future__ import annotations

answer: int = 42
values: list[str]
print(__annotations__)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "{'answer': 'int', 'values': 'list[str]'}\n");
    }

    #[test]
    fn executes_deferred_module_annotations() {
        let source = r"
answer: int = 42
values: list[str]
print(__annotate__(1))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "{'answer': <class 'int'>, 'values': list[str]}\n");
    }

    #[test]
    fn executes_try_except_else_and_named_handlers() {
        let source = r#"
def parse(flag):
    try:
        if flag:
            raise ValueError("bad")
        value = 40
    except ValueError as error:
        value = len(str(error))
    else:
        value += 2
    return value

print(parse(False), parse(True))
"#;
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "42 3\n");
    }

    #[test]
    fn executes_try_finally_on_normal_and_exceptional_paths() {
        let source = r#"
events = []
try:
    events.append("normal")
finally:
    events.append("cleanup-1")

try:
    raise ValueError("bad")
except ValueError:
    events.append("handled")
finally:
    events.append("cleanup-2")

def overriding_return():
    try:
        events.append("value")
        return len(events)
    finally:
        events.append("override")
        return 2

print(events)
print(overriding_return(), events)
"#;
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(
            output,
            "['normal', 'cleanup-1', 'handled', 'cleanup-2']\n2 ['normal', 'cleanup-1', 'handled', 'cleanup-2', 'value', 'override']\n"
        );
    }

    #[test]
    fn executes_context_managers_and_exception_suppression() {
        let source = r#"
events = []
class Manager:
    def __init__(self, suppress):
        self.suppress = suppress
    def __enter__(self):
        events.append("enter")
        return 42
    def __exit__(self, kind, value, traceback):
        events.append("exit")
        return self.suppress

with Manager(False) as value:
    events.append(value)

with Manager(True):
    raise ValueError("suppressed")

print(events)
"#;
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "['enter', 42, 'exit', 'enter', 'exit']\n");
    }

    #[test]
    fn executes_inlined_comprehensions_without_leaking_targets() {
        let source = r"
x = 100
values = [x * 2 for x in [-1, 1, 2] if x > 0]
pairs = {(x, y) for x in [1, 2] for y in [3, 4] if y > 3}
mapping = {x: x * 2 for x in [1, 2]}
print(values, sorted(pairs), mapping, x)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "[2, 4] [(1, 4), (2, 4)] {1: 2, 2: 4} 100\n");
    }

    #[test]
    fn executes_generators_and_generator_expressions() {
        let source = r"
def numbers():
    yield 1
    yield 2

def all_numbers():
    yield from numbers()

def capture():
    list((last := value) for value in numbers())
    return last

yielding_lambda = lambda: (yield 3)
delegating_lambda = lambda: (yield from numbers())

generated = (value * 2 for value in numbers() if value > 1)
print(list(all_numbers()), list(generated), capture(), list(yielding_lambda()), list(delegating_lambda()))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "[1, 2] [4] 2 [3] [1, 2]\n");
    }

    #[test]
    fn executes_coroutines_and_async_generators() {
        let source = r"
import asyncio

async def child():
    return 42

async def numbers():
    yield 1
    yield 2

async def main():
    iterator = numbers()
    return await child(), await anext(iterator), await anext(iterator)

async def collect(stop):
    result = []
    async for number in numbers():
        if number == stop:
            break
        result.append(number)
    else:
        result.append('done')
    return result

events = []

class AsyncManager:
    async def __aenter__(self):
        events.append('enter')
        return 42

    async def __aexit__(self, typ, value, traceback):
        events.append(typ.__name__ if typ else 'exit')
        return typ is ValueError

async def contexts():
    async with AsyncManager() as value:
        events.append(value)
    async with AsyncManager():
        raise ValueError('suppressed')
    return events

async def comprehensions():
    generated = (number async for number in numbers())
    return (
        [number * 2 async for number in numbers() if number > 1],
        {number async for number in numbers()},
        {number: number * 2 async for number in numbers()},
        [number async for number in generated],
    )

def awaited_generator():
    return (await child() for _ in [0, 1])

async def consume_awaited_generator():
    return [value async for value in awaited_generator()]

print(
    asyncio.run(main()),
    asyncio.run(collect(99)),
    asyncio.run(collect(2)),
    asyncio.run(contexts()),
    asyncio.run(comprehensions()),
    asyncio.run(consume_awaited_generator()),
)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(
            output,
            "(42, 1, 2) [1, 2, 'done'] [1] ['enter', 42, 'exit', 'enter', 'ValueError'] ([4], {1, 2}, {1: 2, 2: 4}, [1, 2]) [42, 42]\n"
        );
    }

    #[test]
    fn executes_structural_pattern_matching() {
        let source = r"
class Point:
    __match_args__ = ('x', 'y')

    def __init__(self, x, y):
        self.x = x
        self.y = y

def classify(value):
    match value:
        case None:
            return 'none'
        case (1 | 2) as number:
            return ('number', number)
        case {'x': x, **rest}:
            return ('mapping', x, rest)
        case [first, *middle, last] if first < last:
            return ('sequence', first, middle, last)
        case Point(x, y=0):
            return ('point', x)
        case _:
            return 'other'

print(classify(None))
print(classify(2))
print(classify({'x': 1, 'y': 2}))
print(classify([1, 2, 3, 4]))
print(classify(Point(5, 0)))
print(classify(object()))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(
            output,
            "none\n('number', 2)\n('mapping', 1, {'y': 2})\n('sequence', 1, [2, 3], 4)\n('point', 5)\nother\n"
        );
    }

    #[test]
    fn executes_template_strings() {
        let source = r"
name = 'world'
width = 8
template = t'hello {name!r:>{width}}!'
interpolation = template.interpolations[0]
print(template.strings)
print(interpolation.value, interpolation.expression, interpolation.conversion, interpolation.format_spec)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "('hello ', '!')\nworld name r >8\n");
    }

    #[test]
    fn executes_starred_annotations_and_class_arguments() {
        let source = r"
bases = (object,)
options = {}

class Dynamic(*bases, **options):
    marker = 42

def annotated(*args: *tuple[int]):
    pass

print(Dynamic.marker, annotated.__annotate__(1))
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(output, "42 {'args': *tuple[int]}\n");
    }

    #[test]
    fn executes_type_aliases_and_generic_functions() {
        let source = r"
type Plain = list[int]
type Pair[T] = tuple[T, T]

def identity[T](value: T) -> T:
    return value

def bounded[T: int = bool](value: T) -> T:
    return value

class Box[T]:
    def __init__(self, value):
        self.value = value

print(Plain.__value__, Plain.__type_params__)
print(Pair.__type_params__, Pair[int], Pair[int].__value__)
print(identity(42), identity.__type_params__, identity.__annotate__(1))
print(bounded.__type_params__[0].__bound__, bounded.__type_params__[0].__default__)
print(Box.__type_params__, Box[int], Box[int](42).value)
";
        let Some(output) = execute(source) else {
            return;
        };
        assert_eq!(
            output,
            "list[int] ()\n(T,) Pair[int] tuple[T, T]\n42 (T,) {'value': T, 'return': T}\n<class 'int'> <class 'bool'>\n(T,) __main__.Box[int] 42\n"
        );
    }
}
