[package]
name = "uv-audit-operations"
version = "0.0.91"
description = "This is an internal component crate of uv"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
doctest = false
test = false

[lints]
workspace = true

[dependencies]
uv-audit = { workspace = true }
uv-cache = { workspace = true }
uv-client = { workspace = true }
uv-command-support = { workspace = true }
uv-configuration = { workspace = true }
uv-distribution-types = { workspace = true }
uv-fs = { workspace = true }
uv-lock = { workspace = true }
uv-normalize = { workspace = true }
uv-redacted = { workspace = true }
uv-version = { workspace = true }
uv-warnings = { workspace = true }

anyhow = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
owo-colors = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
