on:
  workflow_call:
    inputs:
      schema-changed:
        required: true
        type: string
      save-rust-cache:
        required: false
        type: string
        default: "true"

permissions: {}

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  cargo-dev-generate-all:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    name: "cargo dev generate-all"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Install Rustfmt"
        run: |
          rustup component add rustfmt
          mkdir -p "$RUNNER_TEMP/rustfmt-bin"
          ln -s "$(rustup which rustfmt)" "$RUNNER_TEMP/rustfmt-bin/rustfmt"
          echo "$RUNNER_TEMP/rustfmt-bin" >> "$GITHUB_PATH"
      - name: "Setup SRS"
        id: srs
        uses: ./.github/actions/setup-srs
      - name: "Generate all"
        run: cargo dev generate-all --mode dry-run
      - name: "Check sysconfig mappings"
        run: cargo dev generate-sysconfig-metadata --mode check
      - name: "Check Packse scenario tests"
        run: cargo dev generate-scenario-tests --mode check
      - name: "Check JSON schema"
        if: ${{ inputs.schema-changed == 'true' }}
        run: cargo dev generate-json-schema --mode check
