on:
  workflow_call:

jobs:
  dist-plan:
    name: "dist plan"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: recursive

      - name: "Install uv"
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.7"
          checksum: "788f18abea7c5f55d6216e4f5613fd89d4d59b631efeec117b2b07fe72f1da21"
          enable-cache: true

      - name: Run dist plan
        run: |
          uv run --locked --only-dev dist plan --output-format=json > plan-dist-manifest.json
          echo "dist plan completed successfully"
          cat plan-dist-manifest.json
