on:
  workflow_call:

permissions: {}

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  cargo-publish-dry-run:
    timeout-minutes: 20
    runs-on: namespace-profile-ubuntu-24-04-8
    name: "cargo publish dry-run"
    steps:
      - uses: namespacelabs/nscloud-checkout-action@445c25d7009680597d73eb03c4e1cd5be522ed73 # v9.0.0
        with:
          persist-credentials: false
      - uses: namespacelabs/nscloud-cache-action@15799a6b54e5765f85b2aac25b3f0df43ed571c0 # v1.4.3
        with:
          cache: rust
      - name: "cargo publish dry-run"
        run: cargo publish --workspace --dry-run
