on:
  workflow_call:
    inputs:
      schema-changed:
        required: true
        type: string
      save-rust-cache:
        required: false
        type: string
        default: "true"

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10
  UV_LOCKED: 1

jobs:
  cargo-dev-generate-all:
    timeout-minutes: 10
    runs-on: ${{ github.repository_owner == 'astral-sh' && 'github-ubuntu-24.04-x86_64-4' || 'ubuntu-latest' }}
    name: "cargo dev generate-all"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: "Install uv"
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.10"
          checksum: "173d95a0c32d18c896c46ba6fafbf3cf9c14ab74b033f81b76c883ef492a976b"
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          save-if: ${{ inputs.save-rust-cache == 'true' }}
      - name: "Generate all"
        run: cargo dev generate-all --mode dry-run
      - name: "Check sysconfig mappings"
        run: cargo dev generate-sysconfig-metadata --mode check
      - name: "Install Rustfmt"
        run: rustup component add rustfmt
      - name: "Check Packse scenario tests"
        run: cargo dev generate-scenario-tests --mode check
      - name: "Check JSON schema"
        if: ${{ inputs.schema-changed == 'true' }}
        run: cargo dev generate-json-schema --mode check
      - name: "Check uv-extract dirhash test vectors"
        run: cargo dev generate-dirhash-test-vectors --mode check
