name: Coverage

on:
  workflow_dispatch:
  workflow_call:

permissions: {}

jobs:
  test:
    uses: $/.github/workflows/test.yml
    with:
      save-rust-cache: "false"
      test-macos: "true"
      collect-coverage: true
